
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Aug 17 22:01:03 CEST 2014
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.semantic.util.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Aug 17 22:01:03 CEST 2014
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\120\000\002\002\004\000\002\045\002\000\002\002" +
    "\004\000\002\003\002\000\002\046\002\000\002\003\011" +
    "\000\002\004\003\000\002\006\004\000\002\006\003\000" +
    "\002\007\004\000\002\007\003\000\002\010\005\000\002" +
    "\010\003\000\002\011\004\000\002\011\003\000\002\047" +
    "\002\000\002\012\010\000\002\024\005\000\002\024\003" +
    "\000\002\013\010\000\002\020\003\000\002\020\003\000" +
    "\002\020\003\000\002\014\006\000\002\023\007\000\002" +
    "\034\004\000\002\034\005\000\002\035\005\000\002\015" +
    "\005\000\002\022\003\000\002\022\003\000\002\022\003" +
    "\000\002\021\003\000\002\021\003\000\002\021\003\000" +
    "\002\016\013\000\002\016\011\000\002\016\011\000\002" +
    "\017\007\000\002\017\005\000\002\017\003\000\002\050" +
    "\002\000\002\005\006\000\002\005\003\000\002\025\003" +
    "\000\002\025\003\000\002\025\003\000\002\051\002\000" +
    "\002\025\004\000\002\025\003\000\002\025\003\000\002" +
    "\037\003\000\002\037\003\000\002\037\005\000\002\037" +
    "\003\000\002\037\003\000\002\037\004\000\002\040\005" +
    "\000\002\040\003\000\002\041\005\000\002\041\005\000" +
    "\002\041\005\000\002\041\003\000\002\041\003\000\002" +
    "\044\005\000\002\044\003\000\002\052\002\000\002\026" +
    "\007\000\002\026\006\000\002\027\005\000\002\027\005" +
    "\000\002\030\010\000\002\030\012\000\002\031\004\000" +
    "\002\032\006\000\002\042\005\000\002\042\003\000\002" +
    "\042\003\000\002\033\014\000\002\043\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\006\002\000\025\000\001\002\000\004\002" +
    "\250\001\002\000\006\002\ufffe\025\007\001\002\000\004" +
    "\002\uffff\001\002\000\004\004\010\001\002\000\004\035" +
    "\ufffd\001\002\000\004\035\012\001\002\000\004\036\013" +
    "\001\002\000\004\022\014\001\002\000\014\004\030\007" +
    "\032\016\031\025\024\033\027\001\002\000\010\007\032" +
    "\016\031\025\024\001\002\000\014\004\030\007\032\016" +
    "\031\025\024\033\027\001\002\000\004\002\ufffb\001\002" +
    "\000\014\004\030\007\032\016\031\025\024\033\027\001" +
    "\002\000\006\040\167\042\235\001\002\000\012\002\ufff5" +
    "\007\ufff5\016\ufff5\025\ufff5\001\002\000\012\002\ufff7\007" +
    "\ufff7\016\ufff7\025\ufff7\001\002\000\004\004\227\001\002" +
    "\000\004\041\225\001\002\000\004\002\ufffc\001\002\000" +
    "\004\004\211\001\002\000\006\040\uffef\042\uffef\001\002" +
    "\000\004\004\157\001\002\000\030\003\ufff2\004\ufff2\005" +
    "\ufff2\013\ufff2\014\ufff2\015\ufff2\017\ufff2\026\ufff2\030\ufff2" +
    "\032\ufff2\035\ufff2\001\002\000\012\002\ufff3\007\ufff3\016" +
    "\ufff3\025\ufff3\001\002\000\004\002\ufff9\001\002\000\030" +
    "\003\uffd8\004\uffd8\005\uffd8\013\uffb2\014\uffd8\015\uffd8\017" +
    "\uffd8\026\uffd8\030\uffd8\032\uffd8\035\uffd8\001\002\000\026" +
    "\003\065\004\054\005\061\014\063\015\067\017\057\026" +
    "\uffd2\030\053\032\055\035\064\001\002\000\004\013\041" +
    "\001\002\000\006\012\uffd6\013\uffd6\001\002\000\004\004" +
    "\042\001\002\000\004\041\043\001\002\000\012\002\ufff1" +
    "\007\ufff1\016\ufff1\025\ufff1\001\002\000\026\023\uffcd\024" +
    "\uffcd\031\uffcd\036\uffcd\037\uffcd\040\uffcd\041\uffcd\043\uffcd" +
    "\044\uffcd\045\uffcd\001\002\000\026\023\uffcb\024\uffcb\031" +
    "\uffcb\036\uffcb\037\uffcb\040\uffcb\041\uffcb\043\uffcb\044\uffcb" +
    "\045\uffcb\001\002\000\004\041\uffd4\001\002\000\004\041" +
    "\uffcf\001\002\000\014\024\103\041\uffd5\043\101\044\100" +
    "\045\102\001\002\000\004\026\147\001\002\000\004\041" +
    "\uffd0\001\002\000\016\003\065\004\073\005\061\014\063" +
    "\032\055\035\064\001\002\000\022\024\uffc0\035\074\041" +
    "\uffc0\043\uffc0\044\uffc0\045\uffc0\046\144\047\uffc0\001\002" +
    "\000\026\023\uffc3\024\uffc3\031\uffc3\036\uffc3\037\uffc3\040" +
    "\uffc3\041\uffc3\043\uffc3\044\uffc3\045\uffc3\001\002\000\026" +
    "\023\uffce\024\uffce\031\uffce\036\uffce\037\uffce\040\uffce\041" +
    "\uffce\043\uffce\044\uffce\045\uffce\001\002\000\016\003\065" +
    "\004\073\005\061\014\063\032\055\035\064\001\002\000" +
    "\004\041\131\001\002\000\026\023\uffc7\024\uffc7\031\uffc7" +
    "\036\uffc7\037\uffc7\040\uffc7\041\uffc7\043\uffc7\044\uffc7\045" +
    "\uffc7\001\002\000\004\041\uffd3\001\002\000\026\023\uffc2" +
    "\024\uffc2\031\uffc2\036\uffc2\037\uffc2\040\uffc2\041\uffc2\043" +
    "\uffc2\044\uffc2\045\uffc2\001\002\000\016\003\065\004\073" +
    "\005\061\014\063\032\055\035\064\001\002\000\004\041" +
    "\126\001\002\000\030\023\uffca\024\uffca\031\uffca\036\uffca" +
    "\037\uffca\040\uffca\041\uffca\043\uffca\044\uffca\045\uffca\047" +
    "\124\001\002\000\004\004\113\001\002\000\004\046\071" +
    "\001\002\000\016\003\065\004\073\005\061\014\063\032" +
    "\055\035\064\001\002\000\014\024\103\041\uffbb\043\101" +
    "\044\100\045\102\001\002\000\032\023\uffc0\024\uffc0\031" +
    "\uffc0\035\074\036\uffc0\037\uffc0\040\uffc0\041\uffc0\043\uffc0" +
    "\044\uffc0\045\uffc0\047\uffc0\001\002\000\022\003\065\004" +
    "\073\005\061\014\063\032\055\035\064\036\uffb2\040\uffb2" +
    "\001\002\000\006\036\111\040\110\001\002\000\006\036" +
    "\uffb4\040\uffb4\001\002\000\016\024\103\036\uffb5\040\uffb5" +
    "\043\101\044\100\045\102\001\002\000\016\003\065\004" +
    "\073\005\061\014\063\032\055\035\064\001\002\000\016" +
    "\003\065\004\073\005\061\014\063\032\055\035\064\001" +
    "\002\000\016\003\065\004\073\005\061\014\063\032\055" +
    "\035\064\001\002\000\016\003\065\004\073\005\061\014" +
    "\063\032\055\035\064\001\002\000\026\023\uffc6\024\uffc6" +
    "\031\uffc6\036\uffc6\037\uffc6\040\uffc6\041\uffc6\043\uffc6\044" +
    "\uffc6\045\uffc6\001\002\000\026\023\uffc4\024\103\031\uffc4" +
    "\036\uffc4\037\uffc4\040\uffc4\041\uffc4\043\uffc4\044\uffc4\045" +
    "\uffc4\001\002\000\026\023\uffc8\024\103\031\uffc8\036\uffc8" +
    "\037\uffc8\040\uffc8\041\uffc8\043\uffc8\044\100\045\102\001" +
    "\002\000\026\023\uffc5\024\103\031\uffc5\036\uffc5\037\uffc5" +
    "\040\uffc5\041\uffc5\043\uffc5\044\uffc5\045\102\001\002\000" +
    "\016\003\065\004\073\005\061\014\063\032\055\035\064" +
    "\001\002\000\026\023\uffb7\024\uffb7\031\uffb7\036\uffb7\037" +
    "\uffb7\040\uffb7\041\uffb7\043\uffb7\044\uffb7\045\uffb7\001\002" +
    "\000\016\024\103\036\uffb6\040\uffb6\043\101\044\100\045" +
    "\102\001\002\000\004\020\114\001\002\000\016\003\065" +
    "\004\073\005\061\014\063\032\055\035\064\001\002\000" +
    "\014\024\103\037\116\043\101\044\100\045\102\001\002" +
    "\000\016\003\065\004\073\005\061\014\063\032\055\035" +
    "\064\001\002\000\014\023\120\024\103\043\101\044\100" +
    "\045\102\001\002\000\030\003\uffd8\004\uffd8\005\uffd8\013" +
    "\uffb2\014\uffd8\015\uffd8\017\uffd8\026\uffd8\030\uffd8\032\uffd8" +
    "\035\uffd8\001\002\000\004\013\122\001\002\000\004\023" +
    "\123\001\002\000\004\041\uffb3\001\002\000\004\004\125" +
    "\001\002\000\030\023\uffc1\024\uffc1\031\uffc1\036\uffc1\037" +
    "\uffc1\040\uffc1\041\uffc1\043\uffc1\044\uffc1\045\uffc1\047\uffc1" +
    "\001\002\000\026\023\uffc9\024\uffc9\031\uffc9\036\uffc9\037" +
    "\uffc9\040\uffc9\041\uffc9\043\uffc9\044\uffc9\045\uffc9\001\002" +
    "\000\014\024\103\036\130\043\101\044\100\045\102\001" +
    "\002\000\026\023\uffcc\024\uffcc\031\uffcc\036\uffcc\037\uffcc" +
    "\040\uffcc\041\uffcc\043\uffcc\044\uffcc\045\uffcc\001\002\000" +
    "\032\003\uffd8\004\uffd8\005\uffd8\012\uffb2\013\uffb2\014\uffd8" +
    "\015\uffd8\017\uffd8\026\uffd8\030\uffd8\032\uffd8\035\uffd8\001" +
    "\002\000\006\012\uffd7\013\uffd7\001\002\000\014\024\103" +
    "\031\134\043\101\044\100\045\102\001\002\000\032\003" +
    "\uffd8\004\uffd8\005\uffd8\012\uffb2\013\uffb2\014\uffd8\015\uffd8" +
    "\017\uffd8\026\uffd8\030\uffd8\032\uffd8\035\uffd8\001\002\000" +
    "\006\012\136\013\137\001\002\000\030\003\uffd8\004\uffd8" +
    "\005\uffd8\013\uffb2\014\uffd8\015\uffd8\017\uffd8\026\uffd8\030" +
    "\uffd8\032\uffd8\035\uffd8\001\002\000\004\017\140\001\002" +
    "\000\004\041\uffba\001\002\000\004\013\142\001\002\000" +
    "\004\017\143\001\002\000\004\041\uffb9\001\002\000\016" +
    "\003\065\004\073\005\061\014\063\032\055\035\064\001" +
    "\002\000\014\024\103\041\uffbc\043\101\044\100\045\102" +
    "\001\002\000\014\024\103\041\uffb8\043\101\044\100\045" +
    "\102\001\002\000\004\035\151\001\002\000\004\041\uffd1" +
    "\001\002\000\020\003\uffbf\004\uffbf\005\uffbf\006\152\014" +
    "\uffbf\032\uffbf\035\uffbf\001\002\000\004\036\156\001\002" +
    "\000\016\003\065\004\073\005\061\014\063\032\055\035" +
    "\064\001\002\000\014\024\103\036\155\043\101\044\100" +
    "\045\102\001\002\000\004\041\uffbe\001\002\000\004\041" +
    "\uffbd\001\002\000\004\035\160\001\002\000\010\004\030" +
    "\036\uffb2\041\uffb2\001\002\000\006\040\167\042\207\001" +
    "\002\000\006\036\164\041\165\001\002\000\006\036\uffd9" +
    "\041\uffd9\001\002\000\006\003\177\030\176\001\002\000" +
    "\004\004\030\001\002\000\006\040\167\042\170\001\002" +
    "\000\004\004\175\001\002\000\010\004\173\010\174\021" +
    "\171\001\002\000\010\022\uffe1\036\uffe1\041\uffe1\001\002" +
    "\000\006\036\uffdb\041\uffdb\001\002\000\010\022\uffdf\036" +
    "\uffdf\041\uffdf\001\002\000\010\022\uffe0\036\uffe0\041\uffe0" +
    "\001\002\000\006\040\ufff0\042\ufff0\001\002\000\010\004" +
    "\173\010\174\021\171\001\002\000\004\022\200\001\002" +
    "\000\010\007\uffdc\016\uffdc\025\uffdc\001\002\000\004\022" +
    "\202\001\002\000\014\004\030\007\032\016\031\025\024" +
    "\033\027\001\002\000\006\040\167\042\205\001\002\000" +
    "\010\007\uffde\016\uffde\025\uffde\001\002\000\010\004\173" +
    "\010\174\021\171\001\002\000\004\041\uffe5\001\002\000" +
    "\010\004\173\010\174\021\171\001\002\000\006\036\uffda" +
    "\041\uffda\001\002\000\004\022\212\001\002\000\004\027" +
    "\213\001\002\000\004\004\030\001\002\000\014\004\uffea" +
    "\007\uffea\016\uffea\025\uffea\033\uffea\001\002\000\004\041" +
    "\224\001\002\000\006\004\030\013\220\001\002\000\004" +
    "\041\223\001\002\000\004\027\221\001\002\000\004\041" +
    "\222\001\002\000\014\004\uffe9\007\uffe9\016\uffe9\025\uffe9" +
    "\033\uffe9\001\002\000\006\004\uffe7\013\uffe7\001\002\000" +
    "\006\004\uffe8\013\uffe8\001\002\000\012\004\030\007\032" +
    "\016\031\025\024\001\002\000\012\002\ufff6\007\ufff6\016" +
    "\ufff6\025\ufff6\001\002\000\004\035\230\001\002\000\010" +
    "\004\030\036\uffb2\041\uffb2\001\002\000\006\036\232\041" +
    "\165\001\002\000\004\022\233\001\002\000\014\004\030" +
    "\007\032\016\031\025\024\033\027\001\002\000\010\007" +
    "\uffdd\016\uffdd\025\uffdd\001\002\000\012\004\173\010\174" +
    "\011\236\021\171\001\002\000\004\046\237\001\002\000" +
    "\010\005\242\014\243\032\241\001\002\000\004\041\244" +
    "\001\002\000\004\041\uffed\001\002\000\004\041\uffeb\001" +
    "\002\000\004\041\uffec\001\002\000\014\004\uffee\007\uffee" +
    "\016\uffee\025\uffee\033\uffee\001\002\000\012\002\ufff8\007" +
    "\ufff8\016\ufff8\025\ufff8\001\002\000\004\002\ufffa\001\002" +
    "\000\012\002\ufff4\007\ufff4\016\ufff4\025\ufff4\001\002\000" +
    "\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\006\002\003\045\004\001\001\000\002\001" +
    "\001\000\004\003\005\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\046\010\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\030\004\025\006\016" +
    "\007\033\010\022\011\021\012\032\013\015\014\017\015" +
    "\024\016\014\024\020\001\001\000\010\011\246\012\032" +
    "\016\014\001\001\000\026\006\245\007\033\010\022\011" +
    "\021\012\032\013\015\014\017\015\024\016\014\024\020" +
    "\001\001\000\002\001\001\000\022\007\244\010\022\011" +
    "\021\012\032\014\017\015\024\016\014\024\202\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\004\047" +
    "\034\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\005\036\043\037\050\035\001\001\000\032\025\057\027" +
    "\045\030\061\031\051\032\044\033\046\036\067\037\047" +
    "\040\055\041\043\044\065\051\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\026\147\001\001\000\002\001\001\000\014\032\044\037" +
    "\145\040\055\041\043\044\065\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\014\032\044\037" +
    "\132\040\055\041\043\044\065\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\032\044\037\126\040\055\041\043\044\065\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\032\044\037\071\040\055\041\043" +
    "\044\065\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\032\044\037\076\040\055\041\043\042\074\043\075" +
    "\044\065\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\032\044\037\106\040\055\041\043" +
    "\044\065\001\001\000\014\032\044\037\105\040\055\041" +
    "\043\044\065\001\001\000\014\032\044\037\104\040\055" +
    "\041\043\044\065\001\001\000\014\032\044\037\103\040" +
    "\055\041\043\044\065\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\032" +
    "\044\037\111\040\055\041\043\044\065\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\032" +
    "\044\037\114\040\055\041\043\044\065\001\001\000\002" +
    "\001\001\000\014\032\044\037\116\040\055\041\043\044" +
    "\065\001\001\000\002\001\001\000\010\005\120\043\037" +
    "\050\035\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\005" +
    "\131\043\037\050\035\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\005\134\043\037\050\035\001\001\000" +
    "\002\001\001\000\010\005\140\043\037\050\035\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\032\044\037\144" +
    "\040\055\041\043\044\065\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\052\152\001\001\000\002\001\001\000\014\032\044\037" +
    "\153\040\055\041\043\044\065\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\017\161\024\160\043\162\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\024\165\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\021\171\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\021\200\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\022\007\203\010\022\011\021" +
    "\012\032\014\017\015\024\016\014\024\202\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\021\205\001\001" +
    "\000\002\001\001\000\004\021\207\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\023\213\001\001\000\010" +
    "\015\214\024\202\034\215\001\001\000\002\001\001\000" +
    "\002\001\001\000\006\015\216\024\202\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\016\010\225" +
    "\011\021\012\032\015\024\016\014\024\202\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\017\230\024\160" +
    "\043\162\001\001\000\002\001\001\000\002\001\001\000" +
    "\022\007\233\010\022\011\021\012\032\014\017\015\024" +
    "\016\014\024\202\001\001\000\002\001\001\000\004\021" +
    "\205\001\001\000\002\001\001\000\004\020\237\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
	
	public void syntax_error(Symbol symbol)
	{ 
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxError ("Error sintactico", token);	    
	}
		
	public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
	{	
		Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxFatalError ("Error fatal", token);
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	
	SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
	SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
	ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
	FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // empty ::= 
            {
              Empty RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("empty",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // sentenciaFor ::= FOR IDENTIFIER IN expresion DOUBLEPOINT expresion LOOP bloqueSentencias END LOOP 
            {
              SentenciaFor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaFor",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // listaParametros ::= empty 
            {
              ListaParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // listaParametros ::= expresion 
            {
              ListaParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // listaParametros ::= listaParametros COMMA expresion 
            {
              ListaParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",32, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // sentenciaLlamadaSubprograma ::= IDENTIFIER LEFTBRACKET listaParametros RIGHTBRACKET 
            {
              SentenciaLlamadaSubprograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaLlamadaSubprograma",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // sentenciaReturn ::= RETURN expresion 
            {
              SentenciaReturn RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaReturn",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // sentenciaIf ::= IF expresion THEN bloqueSentencias ELSE bloqueSentencias END IF 
            {
              SentenciaIf RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIf",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // sentenciaIf ::= IF expresion THEN bloqueSentencias END IF 
            {
              SentenciaIf RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIf",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // sentenciaAsignacion ::= expresionAccesoRegistro ASSIGN expresion 
            {
              SentenciaAsignacion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // sentenciaAsignacion ::= IDENTIFIER ASSIGN expresion 
            {
              SentenciaAsignacion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								semanticErrorManager.semanticDebug ("sentenciaAsignacion -> Id := expresion");
								//Comprobamos si se ha definido el símbolo en la TS anteriormente, si no, mostramos error semántico								
								ScopeIF scope = scopeManager.getCurrentScope();																
								SymbolTableIF tablaSimbolos = scope.getSymbolTable();										
								if(!tablaSimbolos.containsSymbol(id.getLexema())){
									semanticErrorManager.semanticFatalError("ERROR: Variable " + id.getLexema() + " not defined - Line=" + id.getLine() + ",Col=" + id.getColumn());
								}			
								else{
									//Comprobación de tipos.
									SymbolIF symbol = scopeManager.searchSymbol(id.getLexema());
									TypeIF idtype = symbol.getType();
									semanticErrorManager.semanticDebug("El tipo de la variable: " + id.getLexema() + " es: " + idtype.getName());
									//TypeIF exptype = exp.getType();
								}
								SentenciaAsignacion asignacion = new SentenciaAsignacion();
								RESULT = asignacion;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacion",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // sentenciaIO ::= PUTLINE LEFTBRACKET STRING RIGHTBRACKET 
            {
              SentenciaIO RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIO",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // sentenciaIO ::= PUTLINE LEFTBRACKET NT$5 expresion RIGHTBRACKET 
            {
              SentenciaIO RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (SentenciaIO) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expresion expr = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIO",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // NT$5 ::= 
            {
              SentenciaIO RESULT =null;

						SentenciaIO sentenciaIO = new SentenciaIO();
						semanticErrorManager.semanticDebug(" sentenciaIO=PutLine(expresion)" );
						RESULT = sentenciaIO;
					
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$5",40, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // referencia ::= IDENTIFIER 
            {
              Referencia RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("referencia",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // referencia ::= referencia POINT IDENTIFIER 
            {
              Referencia RESULT =null;
		int referleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int referright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Referencia refer = (Referencia)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
									String name = id.getLexema();
									semanticErrorManager.semanticDebug("En Referencia, ref.id: " + refer.getName() + "." + id.getLexema());
									
									TypeIF referType = refer.getType();
									if(referType instanceof TypeRecord)
									{
										TypeRecord tRec = (TypeRecord) referType;
										if(tRec.containsField(name)){
											//TypeIF innerType = tRec.getType();
											//RESULT = new Referencia(innerType, refer.getName());
										}
										else semanticErrorManager.semanticDebug("ERROR R001 - " + refer.getName() + " NO contiene campo " + name);
									}
									else semanticErrorManager.semanticDebug("ERROR R002-" + refer.getName() + ".Tipo=" + refer.getType() + " NO instancia de TypeRecord");
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("referencia",34, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresionLogica ::= FALSE 
            {
              ExpresionLogica RESULT =null;
		
							ExpresionLogica expr = new ExpresionLogica();
							expr.setValue(false);
							semanticErrorManager.semanticDebug("en ExpresiónLógica -> FALSE");
							RESULT = expr;
						
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresionLogica ::= TRUE 
            {
              ExpresionLogica RESULT =null;
		int trleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int trright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token tr = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
							ExpresionLogica expr = new ExpresionLogica();
							expr.setValue(true);
							semanticErrorManager.semanticDebug("en ExpresiónLógica -> TRUE");
							RESULT = expr;
						
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresionLogica ::= expresion EQUAL expresion 
            {
              ExpresionLogica RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								ExpresionLogica exprlog = new ExpresionLogica(e1, e2);
								//Comprobación de tipos sobre e1 y e2
								//Generación de código para e1 = e2
								RESULT=exprlog;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresionLogica ::= expresion GREATTHAN expresion 
            {
              ExpresionLogica RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								ExpresionLogica exprlog = new ExpresionLogica(e1, e2);
								//Comprobación de tipos sobre e1 y e2
								//Generación de código para e1 > e2
								RESULT = exprlog;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresionLogica ::= expresion OR expresion 
            {
              ExpresionLogica RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								ExpresionLogica exprlog = new ExpresionLogica(e1, e2);
								//Comprobación de tipos sobre e1 y e2
								//Generación de código para e1 OR e2							
								RESULT = exprlog;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresionAritmetica ::= NUMBER 
            {
              ExpresionAritmetica RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token num = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
							ExpresionAritmetica exprarit = new ExpresionAritmetica();
							exprarit.setValue(Integer.parseInt(num.getLexema()));
							semanticErrorManager.semanticDebug("En ExpresionAritmetica -> NUMBER");
						
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionAritmetica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresionAritmetica ::= expresion PLUS expresion 
            {
              ExpresionAritmetica RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								semanticErrorManager.semanticDebug("En ExpresionAritmetica -> Expresion + Expresion");
								
//								//Comprobación de tipos sobre e1 y e2
//								TypeIF e1type = scopeManager.searchType("Integer");
//								TypeIF e2type = scopeManager.searchType("Integer");
//								semanticErrorManager.semanticDebug("Expresión Aritmética - Tipo de e1: " + e1type.getName());
//								semanticErrorManager.semanticDebug("Expresión Aritmética - Tipo de e2: " + e2type.getName());
//								if (e1type == e2type)
//								{
//									semanticErrorManager.semanticDebug("Expresión Aritmética - Tipos compatibles" );							
//								}
//								else semanticErrorManager.semanticFatalError ("Expresión Aritmética - Tipos incompatibles");

								ExpresionAritmetica exprarit = new ExpresionAritmetica(e1, e2);
								RESULT = exprarit; 
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionAritmetica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresion ::= error SEMICOLON 
            {
              Expresion RESULT =null;
		
					syntaxErrorManager.syntaxInfo("Error sintáctico en Expresión");
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresion ::= referencia 
            {
              Expresion RESULT =null;
		int refleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int refright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Referencia ref = (Referencia)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
				semanticErrorManager.semanticDebug("en Expresion -> Referencia, Id=" + ref.getName());
					String name = ref.getName();
					if(!scopeManager.containsSymbol(name))
					{
						semanticErrorManager.semanticFatalError("Error. Identificador no definido: " + name); 
						//+ ", [Line=" + id.getLine() + ",Col=" + id.getColumn() + "]");
					}
					else
					{	//Sí existe en la tabla de Símbolos					
						SymbolIF sId = scopeManager.searchSymbol(name);
						TypeIF type = sId.getType();
						RESULT = new Expresion(type);
					}
				
					
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion ::= sentenciaLlamadaSubprograma 
            {
              Expresion RESULT =null;
		
					semanticErrorManager.semanticDebug("en Expresion -> SentenciaLlamadaSubprograma");
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= LEFTBRACKET expresion RIGHTBRACKET 
            {
              Expresion RESULT =null;
		int exprleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int exprright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Expresion expr = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
					semanticErrorManager.semanticDebug("en Expresion -> (expresion) ");
					RESULT = expr;
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion ::= expresionLogica 
            {
              Expresion RESULT =null;
		int exprlogleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int exprlogright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpresionLogica exprlog = (ExpresionLogica)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
					semanticErrorManager.semanticDebug("en Expresion -> ExpresionLogica");
					RESULT = exprlog;
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= expresionAritmetica 
            {
              Expresion RESULT =null;
		int expraritleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expraritright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		ExpresionAritmetica exprarit = (ExpresionAritmetica)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
					semanticErrorManager.semanticDebug("en Expresion -> ExpresionAritmetica: ");
					RESULT = exprarit;
				
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // sentencia ::= sentenciaFor 
            {
              Sentencia RESULT =null;
		 semanticErrorManager.semanticDebug("Sentencia -> SentenciaFor"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // sentencia ::= sentenciaReturn 
            {
              Sentencia RESULT =null;
		 semanticErrorManager.semanticDebug("Sentencia -> SentenciaReturn"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // sentencia ::= NT$4 sentenciaIO 
            {
              Sentencia RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Sentencia) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // NT$4 ::= 
            {
              Sentencia RESULT =null;
 semanticErrorManager.semanticDebug("Sentencia -> sentenciaIO"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$4",39, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sentencia ::= sentenciaIf 
            {
              Sentencia RESULT =null;
		 semanticErrorManager.semanticDebug("Sentencia -> SentenciaIF"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sentencia ::= sentenciaAsignacion 
            {
              Sentencia RESULT =null;
		 semanticErrorManager.semanticDebug("Sentencia->SentenciaAsignación"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // sentencia ::= expresion 
            {
              Sentencia RESULT =null;
		 semanticErrorManager.semanticDebug("Sentencia -> Expresion"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",19, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // bloqueSentencias ::= empty 
            {
              BloqueSentencias RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueSentencias",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // bloqueSentencias ::= NT$3 sentencia SEMICOLON bloqueSentencias 
            {
              BloqueSentencias RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (BloqueSentencias) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int sentleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int sentright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Sentencia sent = (Sentencia)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueSentencias",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // NT$3 ::= 
            {
              BloqueSentencias RESULT =null;

									semanticErrorManager.semanticDebug("Sentencia: ");
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$3",38, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // bloqueParamSubprograma ::= empty 
            {
              BloqueParamSubprograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueParamSubprograma",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // bloqueParamSubprograma ::= listaIdentificadores COLON tipoPrimitivo 
            {
              BloqueParamSubprograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueParamSubprograma",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // bloqueParamSubprograma ::= bloqueParamSubprograma SEMICOLON listaIdentificadores COLON tipoPrimitivo 
            {
              BloqueParamSubprograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueParamSubprograma",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // declaracionSubprograma ::= FUNCTION IDENTIFIER LEFTBRACKET bloqueParamSubprograma RIGHTBRACKET error IS 
            {
              DeclaracionSubprograma RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 00x: Error definición función, falta return");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprograma",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // declaracionSubprograma ::= PROCEDURE IDENTIFIER LEFTBRACKET bloqueParamSubprograma RIGHTBRACKET IS seccionTipos 
            {
              DeclaracionSubprograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprograma",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // declaracionSubprograma ::= FUNCTION IDENTIFIER LEFTBRACKET bloqueParamSubprograma RIGHTBRACKET RETURN tipoPrimitivo IS seccionTipos 
            {
              DeclaracionSubprograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprograma",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // tipoPrimitivo ::= IDENTIFIER 
            {
              TipoPrimitivo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			TipoPrimitivo tipoPrim = new TipoPrimitivo("IDENTIFIER");
									RESULT = tipoPrim;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // tipoPrimitivo ::= BOOLEAN 
            {
              TipoPrimitivo RESULT =null;
		int tpboolleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tpboolright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token tpbool = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 TipoPrimitivo tipoPrim = new TipoPrimitivo(tpbool.getLexema().toUpperCase());
								 	RESULT = tipoPrim;
								 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // tipoPrimitivo ::= INTEGER 
            {
              TipoPrimitivo RESULT =null;
		int tpintleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tpintright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token tpint = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 TipoPrimitivo tipoPrim = new TipoPrimitivo(tpint.getLexema().toUpperCase());
								 	RESULT = tipoPrim;
								 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tipo ::= IDENTIFIER 
            {
              Tipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // tipo ::= BOOLEAN 
            {
              Tipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipo ::= INTEGER 
            {
              Tipo RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipo",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declaracionVariable ::= listaIdentificadores COLON tipoPrimitivo 
            {
              DeclaracionVariable RESULT =null;
		int lidleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int lidright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ListaIdentificadores lid = (ListaIdentificadores)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tpright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TipoPrimitivo tp = (TipoPrimitivo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			//	Obtenemos ámbito actual
								ScopeIF scope = scopeManager.getCurrentScope();
								semanticErrorManager.semanticDebug("Sección Declaración Variables: Scope actual, nombre:" + scope.getName());
								
								// Obtenemos la tabla de símbolos del ámbito actual, y verificamos si los identificadores de la lista de variables están ya definidos en la TS
								SymbolTableIF tablaSimbolos = scope.getSymbolTable();
								semanticErrorManager.semanticDebug("Sección Variables - Tabla símbolos del scope:" + scope.getName() + " obtenida. Tamaño TS: " + tablaSimbolos.getSize());
								ArrayList<String> identifiersList = lid.getIdentifiersList();
								semanticErrorManager.semanticDebug("Sección Variables - Tras obtener lista de Identificadores como ArrayList. Tamaño ArrayList=" + identifiersList.size());
								semanticErrorManager.semanticDebug("Sección Variables - Tamaño de listadeIdentificadores declaración variables=" + identifiersList.size());
								for(int i = 0; i<identifiersList.size(); i++){
									if(tablaSimbolos.containsSymbol(identifiersList.get(i)))
										semanticErrorManager.semanticFatalError("Error en declaración de Variable, ya existe declaración de " + identifiersList.get(i));
									else{ 
										TypeIF tipo = scopeManager.searchType(tp.getValue());
										SymbolVariable symbolvariable = new SymbolVariable(scope, identifiersList.get(i), tipo);
										tablaSimbolos.addSymbol(symbolvariable);
									}
								}
								semanticErrorManager.semanticDebug("*** FIN Sección Declaración Variables: Scope actual, nombre:" + scope.getName());
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariable",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // campoRegistro ::= IDENTIFIER COLON tipoPrimitivo 
            {
              CampoRegistro RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tpright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TipoPrimitivo tp = (TipoPrimitivo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			//Campo es de tipo Integer o Boolean	
							//Comprobamos si el simbolo está ya definido en la tabla de símbolos
							
								ScopeIF scope = scopeManager.getCurrentScope();								
								SymbolTableIF tablaSimbolos = scope.getSymbolTable();
								TypeTableIF tablaTipos = scope.getTypeTable();
								
								if(tablaSimbolos.containsSymbol(id.getLexema()))
									semanticErrorManager.semanticFatalError("ERROR T02: Campo de registro: " + id.getLexema() + "ya definido anteriormente");
								else{
									CampoRegistro camporeg = new CampoRegistro(id.getLexema(), tp);
									TypeIF tipo = scopeManager.searchType(tp.getValue());
									SymbolVariable symbolvariable = new SymbolVariable(scope, id.getLexema(), tipo);
									semanticErrorManager.semanticDebug("Después symbolvariable: ");
									semanticErrorManager.semanticDebug("El tipo es: tp.getValue()=" + tp.getValue());
									Util util = new Util();
									util.debugTablesToString(scope);
									
									if(!tablaTipos.containsType(tipo))
									{//Si tipo no existe en tabla de tipos, mostramos error semántico
										semanticErrorManager.semanticFatalError("ERROR T03: Campo de registro: " + id.getLexema() + " de tipo desconocido " + tp.getValue());
									}
									else{	//Añadimos el identificador a la tabla de símbolos, en el ámbito actual
										//CampoRegistro camporeg = new CampoRegistro(id.getLexema(), tp);
										tablaSimbolos.addSymbol(id.getLexema(), symbolvariable);
										RESULT = camporeg;
										}
								}

							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("campoRegistro",27, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // bloqueCamposRegistro ::= bloqueCamposRegistro declaracionVariable SEMICOLON 
            {
              BloqueCamposRegistro RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueCamposRegistro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // bloqueCamposRegistro ::= declaracionVariable SEMICOLON 
            {
              BloqueCamposRegistro RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueCamposRegistro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // tipoRegistro ::= RECORD bloqueCamposRegistro END RECORD SEMICOLON 
            {
              TipoRegistro RESULT =null;
		int bcrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int bcrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		BloqueCamposRegistro bcr = (BloqueCamposRegistro)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		
								//Creamos nuevo tipo Registro y lo introducimos en la tabla de tipos							
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoRegistro",17, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // declaracionTipo ::= TYPE IDENTIFIER IS tipoRegistro 
            {
              DeclaracionTipo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tipoRegleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tipoRegright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TipoRegistro tipoReg = (TipoRegistro)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								semanticErrorManager.semanticDebug("**Declaración Tipo: " + id.getLexema() + "******");
								semanticErrorManager.semanticDebug("**********************************");
								// Obtenemos la tabla de tipos del ámbito actual,y verificamos si el tipo está definido ya en TT, si no, lo añadimos
								ScopeIF scope = scopeManager.getCurrentScope();								
								TypeTableIF tablaTipos = scope.getTypeTable();
								if(tablaTipos.containsType(id.getLexema()))
										semanticErrorManager.semanticFatalError("ERROR - Error en declaración de Tipo, ya existe declaración de " + id.getLexema());
								else{ 
									
								}
								semanticErrorManager.semanticDebug("FIN**Declaración Tipo: " + id.getLexema() + "******");
								semanticErrorManager.semanticDebug("**********************************");										
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTipo",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // valorConstante ::= NUMBER 
            {
              ValorConstante RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token num = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 	
				   	 		ValorConstante value = new ValorConstante(num.getLexema());
				   	 		RESULT = value;
				   	 	
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConstante",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // valorConstante ::= FALSE 
            {
              ValorConstante RESULT =null;
		int vcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vcright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token vc = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			ValorConstante value = new ValorConstante(vc.getLexema());
				   			RESULT = value; 
				   		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConstante",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // valorConstante ::= TRUE 
            {
              ValorConstante RESULT =null;
		int vcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vcright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token vc = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
							ValorConstante value = new ValorConstante(vc.getLexema());
					   		RESULT = value; 
					   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConstante",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // declaracionConstante ::= listaIdentificadores COLON CONSTANT ASSIGN valorConstante SEMICOLON 
            {
              DeclaracionConstante RESULT =null;
		int lidleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int lidright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		ListaIdentificadores lid = (ListaIdentificadores)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int vcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vcright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ValorConstante vc = (ValorConstante)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		syntaxErrorManager.syntaxDebug("En declaración constante");
							
								//	Obtenemos ámbito actual
								ScopeIF scope = scopeManager.getCurrentScope();
								semanticErrorManager.semanticDebug("Scope actual, nombre:" + scope.getName());
								// Obtenemos la tabla de símbolos del ámbito actual
								SymbolTableIF tablaSimbolos = scope.getSymbolTable();
								
								// Obtenemos lista de identificadores
								ArrayList<String> identifiersList = lid.getIdentifiersList();
								
								//Verificamos si los identificadores de la lista están ya definidos en la TS. 
								for(int i = 0; i<identifiersList.size(); i++){
									if(tablaSimbolos.containsSymbol(identifiersList.get(i)))
										semanticErrorManager.semanticFatalError("Error en declaración de Constante, ya existe declaración de " + identifiersList.get(i));
									else{
										// Símbolos no existen en TS, por lo que añadimos cada uno de ellos a la TS.		
										// SymbolConstant(scope, name, type)
										TypeIF typeInTT = scopeManager.searchType("Boolean");
										SymbolConstant symbolconstant = new SymbolConstant(scope, identifiersList.get(i), typeInTT);
										tablaSimbolos.addSymbol(symbolconstant);
									}
								}
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstante",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // listaIdentificadores ::= IDENTIFIER 
            {
              ListaIdentificadores RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			
						  	//Creamos lista de identificadores, e insertamos el primer elemento id.
						  	ListaIdentificadores idlist = new ListaIdentificadores();
						  	idlist.addIdentifier(id.getLexema());
						  	RESULT=idlist;
						  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaIdentificadores",18, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // listaIdentificadores ::= listaIdentificadores COMMA IDENTIFIER 
            {
              ListaIdentificadores RESULT =null;
		int idlistleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idlistright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ListaIdentificadores idlist = (ListaIdentificadores)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
							String name = id.getLexema();
							//Verificamos si el identificador está en la tabla de símbolos
							if(scopeManager.containsSymbol(name)){
								//Si existe el símbolo en ámbitos abiertos, lo obtenemos,
								SymbolIF sym = scopeManager.searchSymbol(name);
								if (sym instanceof SymbolConstant){
									SymbolConstant symconst = (SymbolConstant)sym;
									Object value = symconst.getValue();
									//RESULT = new RNumero(value);
								}
								else
									semanticErrorManager.semanticFatalError("Símbolo no es de tipo SymbolConstant");
							}
							else{
								//Añadimos identificador a lista de identificadores
								idlist.addIdentifier(id.getLexema());
								RESULT=idlist;
								}					
						
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaIdentificadores",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // seccionCuerpoPrograma ::= BEGIN NT$2 bloqueSentencias END IDENTIFIER SEMICOLON 
            {
              SeccionCuerpoPrograma RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (SeccionCuerpoPrograma) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		
									semanticErrorManager.semanticDebug("*******************Fin BloqueSentencias************************");
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionCuerpoPrograma",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$2 ::= 
            {
              SeccionCuerpoPrograma RESULT =null;
 semanticErrorManager.semanticDebug("*******************Inicio BloqueSentencias*******************"); 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$2",37, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // seccionSubprogramas ::= seccionCuerpoPrograma 
            {
              SeccionSubprogramas RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionSubprogramas",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // seccionSubprogramas ::= declaracionSubprograma seccionSubprogramas 
            {
              SeccionSubprogramas RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionSubprogramas",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // seccionVariables ::= seccionSubprogramas 
            {
              SeccionVariables RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionVariables",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // seccionVariables ::= declaracionVariable SEMICOLON seccionVariables 
            {
              SeccionVariables RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionVariables",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // seccionTipos ::= seccionVariables 
            {
              SeccionTipos RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionTipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // seccionTipos ::= declaracionTipo seccionTipos 
            {
              SeccionTipos RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionTipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // seccionConstantes ::= seccionTipos 
            {
              SeccionConstantes RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionConstantes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // seccionConstantes ::= declaracionConstante seccionConstantes 
            {
              SeccionConstantes RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionConstantes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaraciones ::= seccionConstantes 
            {
              Declaraciones RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // axiom ::= PROCEDURE IDENTIFIER NT$1 LEFTBRACKET RIGHTBRACKET IS declaraciones 
            {
              Axiom RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Axiom) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Declaraciones d = (Declaraciones)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // NT$1 ::= 
            {
              Axiom RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

			//Creación del ámbito global del programa
				String name = id.getLexema();
				scopeManager.openScope(name);
				ScopeIF scope = scopeManager.getCurrentScope();
				semanticErrorManager.semanticDebug("El nombre del scope creado es: " + scope.getName());
				
				//Obtenemos la tabla de tipos del ámbito actual
				TypeTableIF tablaTipos = scope.getTypeTable();
				semanticErrorManager.semanticDebug("Tabla de tipos obtenida, pertenece al scope/ámbito: " + tablaTipos.getScope().getName() + " y tiene tamaño: " + tablaTipos.getSize()); 
				
				//Insertar todos los TypeSimple en la Tabla de Tipos
				TypeSimple typeBoolean = new TypeSimple(scope, "Boolean");
				TypeSimple typeInteger = new TypeSimple(scope, "Integer");
				tablaTipos.addType("BOOLEAN", typeBoolean);
				tablaTipos.addType("INTEGER", typeInteger); 
				semanticErrorManager.semanticDebug("Tabla de tipos obtenida del scope/ámbito: " + tablaTipos.getScope().getName() + " y tiene tamaño: " + tablaTipos.getSize());
				List<TypeIF> listaTipos = tablaTipos.getTypes();
				semanticErrorManager.semanticDebug("TT contiente tipo Boolean??" + tablaTipos.containsType("Boolean"));
					semanticErrorManager.semanticDebug("TT contiente tipo Integer??" + tablaTipos.containsType("Integer"));
					semanticErrorManager.semanticDebug("TT contiente tipo Pepe??" + tablaTipos.containsType("Pepe"));
				for (int i=0; i<listaTipos.size(); i++){
					semanticErrorManager.semanticDebug("Nombre de tipo: " + listaTipos.get(i).getName());
				}
				
				//scopeManager.closeScope();
				//semanticErrorManager.semanticDebug("Scope cerrado: " + scope.getName());
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",36, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
  		// No modificar esta estructura, aunque se pueden añadir más acciones semánticas
  		
  		//List intermediateCode = ax.getIntermediateCode ();
  		//finalCodeFactory.create (intermediateCode);

  		
  		syntaxErrorManager.syntaxInfo ("Parsing process ended.");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
 
        syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",35, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

