
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Aug 06 21:17:17 CEST 2014
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Aug 06 21:17:17 CEST 2014
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\117\000\002\002\004\000\002\043\002\000\002\002" +
    "\004\000\002\003\002\000\002\003\010\000\002\003\011" +
    "\000\002\003\010\000\002\004\003\000\002\006\004\000" +
    "\002\006\003\000\002\007\004\000\002\007\003\000\002" +
    "\010\004\000\002\010\003\000\002\011\004\000\002\011" +
    "\003\000\002\012\007\000\002\012\007\000\002\012\003" +
    "\000\002\022\005\000\002\022\003\000\002\013\010\000" +
    "\002\013\007\000\002\013\007\000\002\013\011\000\002" +
    "\020\003\000\002\020\003\000\002\020\003\000\002\014" +
    "\012\000\002\032\004\000\002\032\005\000\002\033\005" +
    "\000\002\015\006\000\002\021\003\000\002\021\003\000" +
    "\002\021\003\000\002\016\013\000\002\016\011\000\002" +
    "\016\011\000\002\017\007\000\002\017\005\000\002\017" +
    "\003\000\002\005\005\000\002\005\003\000\002\023\003" +
    "\000\002\023\003\000\002\023\003\000\002\023\003\000" +
    "\002\023\003\000\002\023\003\000\002\036\003\000\002" +
    "\036\003\000\002\036\003\000\002\036\005\000\002\036" +
    "\003\000\002\037\005\000\002\037\003\000\002\040\005" +
    "\000\002\040\005\000\002\040\005\000\002\040\003\000" +
    "\002\040\003\000\002\040\003\000\002\034\005\000\002" +
    "\034\005\000\002\024\006\000\002\035\003\000\002\035" +
    "\003\000\002\025\005\000\002\025\005\000\002\026\010" +
    "\000\002\026\012\000\002\027\004\000\002\030\006\000" +
    "\002\041\005\000\002\041\003\000\002\041\003\000\002" +
    "\031\014\000\002\042\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\260\000\006\002\000\025\000\001\002\000\004\002" +
    "\262\001\002\000\006\002\ufffe\025\007\001\002\000\004" +
    "\002\uffff\001\002\000\004\004\010\001\002\000\004\035" +
    "\011\001\002\000\006\003\013\036\012\001\002\000\006" +
    "\003\256\022\257\001\002\000\004\036\014\001\002\000" +
    "\004\022\015\001\002\000\016\003\030\004\031\007\034" +
    "\016\032\025\024\033\027\001\002\000\012\003\030\007" +
    "\034\016\032\025\024\001\002\000\016\003\030\004\031" +
    "\007\034\016\032\025\024\033\027\001\002\000\004\002" +
    "\ufffa\001\002\000\006\040\160\042\237\001\002\000\014" +
    "\002\ufff6\003\ufff6\007\ufff6\016\ufff6\025\ufff6\001\002\000" +
    "\014\002\ufff4\003\ufff4\007\ufff4\016\ufff4\025\ufff4\001\002" +
    "\000\004\004\231\001\002\000\004\002\ufffc\001\002\000" +
    "\014\003\030\004\031\007\034\016\032\025\024\001\002" +
    "\000\004\004\212\001\002\000\014\002\uffef\003\uffef\007" +
    "\uffef\016\uffef\025\uffef\001\002\000\006\040\uffed\042\uffed" +
    "\001\002\000\004\004\170\001\002\000\016\003\030\004" +
    "\031\007\034\016\032\025\024\033\027\001\002\000\026" +
    "\004\050\005\057\013\uffb3\014\061\015\063\017\054\026" +
    "\046\030\047\032\052\035\062\001\002\000\014\002\ufff2" +
    "\003\ufff2\007\ufff2\016\ufff2\025\ufff2\001\002\000\004\002" +
    "\ufff8\001\002\000\004\013\151\001\002\000\026\023\uffce" +
    "\024\uffce\031\uffce\036\uffce\037\uffce\040\uffce\041\uffce\043" +
    "\uffce\044\uffce\045\uffce\001\002\000\026\023\uffc5\024\uffc5" +
    "\031\uffc5\036\uffc5\037\uffc5\040\uffc5\041\uffc5\043\uffc5\044" +
    "\uffc5\045\uffc5\001\002\000\004\041\uffd2\001\002\000\004" +
    "\041\uffd4\001\002\000\004\041\uffd0\001\002\000\014\024" +
    "\101\041\uffd5\043\077\044\076\045\100\001\002\000\004" +
    "\035\144\001\002\000\014\004\067\005\057\014\061\032" +
    "\052\035\062\001\002\000\022\024\uffcb\035\072\041\uffcb" +
    "\043\uffcb\044\uffcb\045\uffcb\046\141\047\071\001\002\000" +
    "\004\041\uffd1\001\002\000\026\023\uffc4\024\uffc4\031\uffc4" +
    "\036\uffc4\037\uffc4\040\uffc4\041\uffc4\043\uffc4\044\uffc4\045" +
    "\uffc4\001\002\000\026\023\uffcf\024\uffcf\031\uffcf\036\uffcf" +
    "\037\uffcf\040\uffcf\041\uffcf\043\uffcf\044\uffcf\045\uffcf\001" +
    "\002\000\014\004\067\005\057\014\061\032\052\035\062" +
    "\001\002\000\006\012\uffd6\013\uffd6\001\002\000\004\041" +
    "\126\001\002\000\026\023\uffc9\024\uffc9\031\uffc9\036\uffc9" +
    "\037\uffc9\040\uffc9\041\uffc9\043\uffc9\044\uffc9\045\uffc9\001" +
    "\002\000\004\041\uffd3\001\002\000\026\023\uffc3\024\uffc3" +
    "\031\uffc3\036\uffc3\037\uffc3\040\uffc3\041\uffc3\043\uffc3\044" +
    "\uffc3\045\uffc3\001\002\000\014\004\067\005\057\014\061" +
    "\032\052\035\062\001\002\000\004\004\113\001\002\000" +
    "\016\024\uffcd\041\uffcd\043\uffcd\044\uffcd\045\uffcd\046\065" +
    "\001\002\000\014\004\067\005\057\014\061\032\052\035" +
    "\062\001\002\000\014\024\101\041\uffbc\043\077\044\076" +
    "\045\100\001\002\000\032\023\uffcb\024\uffcb\031\uffcb\035" +
    "\072\036\uffcb\037\uffcb\040\uffcb\041\uffcb\043\uffcb\044\uffcb" +
    "\045\uffcb\047\071\001\002\000\026\023\uffcd\024\uffcd\031" +
    "\uffcd\036\uffcd\037\uffcd\040\uffcd\041\uffcd\043\uffcd\044\uffcd" +
    "\045\uffcd\001\002\000\004\004\111\001\002\000\020\004" +
    "\067\005\057\014\061\032\052\035\062\036\uffb3\040\uffb3" +
    "\001\002\000\006\036\107\040\106\001\002\000\006\036" +
    "\uffb5\040\uffb5\001\002\000\016\024\101\036\uffb6\040\uffb6" +
    "\043\077\044\076\045\100\001\002\000\014\004\067\005" +
    "\057\014\061\032\052\035\062\001\002\000\014\004\067" +
    "\005\057\014\061\032\052\035\062\001\002\000\014\004" +
    "\067\005\057\014\061\032\052\035\062\001\002\000\014" +
    "\004\067\005\057\014\061\032\052\035\062\001\002\000" +
    "\026\023\uffc8\024\uffc8\031\uffc8\036\uffc8\037\uffc8\040\uffc8" +
    "\041\uffc8\043\uffc8\044\uffc8\045\uffc8\001\002\000\026\023" +
    "\uffc6\024\101\031\uffc6\036\uffc6\037\uffc6\040\uffc6\041\uffc6" +
    "\043\uffc6\044\uffc6\045\uffc6\001\002\000\026\023\uffca\024" +
    "\101\031\uffca\036\uffca\037\uffca\040\uffca\041\uffca\043\uffca" +
    "\044\076\045\100\001\002\000\026\023\uffc7\024\101\031" +
    "\uffc7\036\uffc7\037\uffc7\040\uffc7\041\uffc7\043\uffc7\044\uffc7" +
    "\045\100\001\002\000\014\004\067\005\057\014\061\032" +
    "\052\035\062\001\002\000\026\023\uffb8\024\uffb8\031\uffb8" +
    "\036\uffb8\037\uffb8\040\uffb8\041\uffb8\043\uffb8\044\uffb8\045" +
    "\uffb8\001\002\000\016\024\101\036\uffb7\040\uffb7\043\077" +
    "\044\076\045\100\001\002\000\032\023\uffc1\024\uffc1\031" +
    "\uffc1\036\uffc1\037\uffc1\040\uffc1\041\uffc1\043\uffc1\044\uffc1" +
    "\045\uffc1\046\uffc1\047\071\001\002\000\030\023\uffc2\024" +
    "\uffc2\031\uffc2\036\uffc2\037\uffc2\040\uffc2\041\uffc2\043\uffc2" +
    "\044\uffc2\045\uffc2\046\uffc2\001\002\000\004\020\114\001" +
    "\002\000\014\004\067\005\057\014\061\032\052\035\062" +
    "\001\002\000\014\024\101\037\116\043\077\044\076\045" +
    "\100\001\002\000\014\004\067\005\057\014\061\032\052" +
    "\035\062\001\002\000\014\023\120\024\101\043\077\044" +
    "\076\045\100\001\002\000\026\004\050\005\057\013\uffb3" +
    "\014\061\015\063\017\054\026\046\030\047\032\052\035" +
    "\062\001\002\000\004\013\122\001\002\000\004\023\123" +
    "\001\002\000\004\041\uffb4\001\002\000\014\024\101\036" +
    "\125\043\077\044\076\045\100\001\002\000\026\023\uffcc" +
    "\024\uffcc\031\uffcc\036\uffcc\037\uffcc\040\uffcc\041\uffcc\043" +
    "\uffcc\044\uffcc\045\uffcc\001\002\000\030\004\050\005\057" +
    "\012\uffb3\013\uffb3\014\061\015\063\017\054\026\046\030" +
    "\047\032\052\035\062\001\002\000\006\012\uffd7\013\uffd7" +
    "\001\002\000\014\024\101\031\131\043\077\044\076\045" +
    "\100\001\002\000\030\004\050\005\057\012\uffb3\013\uffb3" +
    "\014\061\015\063\017\054\026\046\030\047\032\052\035" +
    "\062\001\002\000\006\012\133\013\134\001\002\000\026" +
    "\004\050\005\057\013\uffb3\014\061\015\063\017\054\026" +
    "\046\030\047\032\052\035\062\001\002\000\004\017\135" +
    "\001\002\000\004\041\uffbb\001\002\000\004\013\137\001" +
    "\002\000\004\017\140\001\002\000\004\041\uffba\001\002" +
    "\000\014\004\067\005\057\014\061\032\052\035\062\001" +
    "\002\000\014\024\101\041\uffbd\043\077\044\076\045\100" +
    "\001\002\000\014\024\101\041\uffb9\043\077\044\076\045" +
    "\100\001\002\000\016\004\067\005\057\006\146\014\061" +
    "\032\052\035\062\001\002\000\004\036\150\001\002\000" +
    "\004\036\uffbe\001\002\000\014\024\101\036\uffbf\043\077" +
    "\044\076\045\100\001\002\000\004\041\uffc0\001\002\000" +
    "\006\003\152\004\153\001\002\000\004\041\155\001\002" +
    "\000\004\041\154\001\002\000\014\002\ufff1\003\ufff1\007" +
    "\ufff1\016\ufff1\025\ufff1\001\002\000\014\002\ufff0\003\ufff0" +
    "\007\ufff0\016\ufff0\025\ufff0\001\002\000\006\040\160\042" +
    "\161\001\002\000\014\002\ufff7\003\ufff7\007\ufff7\016\ufff7" +
    "\025\ufff7\001\002\000\004\004\167\001\002\000\010\004" +
    "\164\010\165\021\162\001\002\000\010\022\uffe0\036\uffe0" +
    "\041\uffe0\001\002\000\004\041\166\001\002\000\010\022" +
    "\uffde\036\uffde\041\uffde\001\002\000\010\022\uffdf\036\uffdf" +
    "\041\uffdf\001\002\000\014\003\uffe1\004\uffe1\007\uffe1\016" +
    "\uffe1\025\uffe1\001\002\000\006\040\uffee\042\uffee\001\002" +
    "\000\004\035\171\001\002\000\010\004\031\036\uffb3\041" +
    "\uffb3\001\002\000\006\040\160\042\210\001\002\000\006" +
    "\036\175\041\176\001\002\000\006\036\uffd8\041\uffd8\001" +
    "\002\000\006\003\202\030\203\001\002\000\004\004\031" +
    "\001\002\000\006\040\160\042\200\001\002\000\010\004" +
    "\164\010\165\021\162\001\002\000\006\036\uffda\041\uffda" +
    "\001\002\000\004\022\207\001\002\000\010\004\164\010" +
    "\165\021\162\001\002\000\004\022\205\001\002\000\016" +
    "\003\030\004\031\007\034\016\032\025\024\033\027\001" +
    "\002\000\012\003\uffdd\007\uffdd\016\uffdd\025\uffdd\001\002" +
    "\000\012\003\uffdb\007\uffdb\016\uffdb\025\uffdb\001\002\000" +
    "\010\004\164\010\165\021\162\001\002\000\006\036\uffd9" +
    "\041\uffd9\001\002\000\004\022\213\001\002\000\004\027" +
    "\214\001\002\000\004\004\215\001\002\000\004\042\226" +
    "\001\002\000\004\041\225\001\002\000\006\004\215\013" +
    "\221\001\002\000\004\041\224\001\002\000\004\027\222" +
    "\001\002\000\004\041\223\001\002\000\016\003\uffe5\004" +
    "\uffe5\007\uffe5\016\uffe5\025\uffe5\033\uffe5\001\002\000\006" +
    "\004\uffe3\013\uffe3\001\002\000\006\004\uffe4\013\uffe4\001" +
    "\002\000\010\004\164\010\165\021\162\001\002\000\004" +
    "\041\uffe2\001\002\000\014\002\ufff5\003\ufff5\007\ufff5\016" +
    "\ufff5\025\ufff5\001\002\000\004\035\232\001\002\000\010" +
    "\004\031\036\uffb3\041\uffb3\001\002\000\006\036\234\041" +
    "\176\001\002\000\004\022\235\001\002\000\016\003\030" +
    "\004\031\007\034\016\032\025\024\033\027\001\002\000" +
    "\012\003\uffdc\007\uffdc\016\uffdc\025\uffdc\001\002\000\012" +
    "\004\164\010\165\011\240\021\162\001\002\000\006\003" +
    "\241\046\242\001\002\000\010\005\246\014\247\032\245" +
    "\001\002\000\012\003\243\005\246\014\247\032\245\001" +
    "\002\000\016\003\uffea\004\uffea\007\uffea\016\uffea\025\uffea" +
    "\033\uffea\001\002\000\006\003\251\041\250\001\002\000" +
    "\020\003\uffe8\004\uffe8\007\uffe8\016\uffe8\025\uffe8\033\uffe8" +
    "\041\uffe8\001\002\000\020\003\uffe6\004\uffe6\007\uffe6\016" +
    "\uffe6\025\uffe6\033\uffe6\041\uffe6\001\002\000\020\003\uffe7" +
    "\004\uffe7\007\uffe7\016\uffe7\025\uffe7\033\uffe7\041\uffe7\001" +
    "\002\000\016\003\uffec\004\uffec\007\uffec\016\uffec\025\uffec" +
    "\033\uffec\001\002\000\004\041\252\001\002\000\016\003" +
    "\uffe9\004\uffe9\007\uffe9\016\uffe9\025\uffe9\033\uffe9\001\002" +
    "\000\016\003\uffeb\004\uffeb\007\uffeb\016\uffeb\025\uffeb\033" +
    "\uffeb\001\002\000\004\002\ufff9\001\002\000\014\002\ufff3" +
    "\003\ufff3\007\ufff3\016\ufff3\025\ufff3\001\002\000\016\003" +
    "\030\004\031\007\034\016\032\025\024\033\027\001\002" +
    "\000\016\003\030\004\031\007\034\016\032\025\024\033" +
    "\027\001\002\000\004\002\ufffd\001\002\000\004\002\ufffb" +
    "\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\260\000\006\002\003\043\004\001\001\000\002\001" +
    "\001\000\004\003\005\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\030\004\024" +
    "\006\017\007\035\010\021\011\022\012\034\013\016\014" +
    "\032\015\025\016\015\022\020\001\001\000\010\011\254" +
    "\012\034\016\015\001\001\000\026\006\253\007\035\010" +
    "\021\011\022\012\034\013\016\014\032\015\025\016\015" +
    "\022\020\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\016\010\227\011\022\012\034\015\025\016" +
    "\015\022\155\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\007\156\010" +
    "\021\011\022\012\034\014\032\015\025\016\015\022\155" +
    "\001\001\000\034\005\036\023\055\024\041\025\042\026" +
    "\057\027\050\030\040\031\043\034\063\036\044\037\052" +
    "\040\037\042\054\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\014\030\040\034\067" +
    "\036\142\037\052\040\037\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\014" +
    "\030\040\034\067\036\127\037\052\040\037\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\030\040\034\067\036" +
    "\123\037\052\040\037\001\001\000\002\001\001\000\002" +
    "\001\001\000\014\030\040\034\067\036\065\037\052\040" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\034\111\001\001\000\020\030\040\034" +
    "\067\036\074\037\052\040\037\041\072\042\073\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\030\040\034\067\036\104\037\052\040\037\001\001" +
    "\000\014\030\040\034\067\036\103\037\052\040\037\001" +
    "\001\000\014\030\040\034\067\036\102\037\052\040\037" +
    "\001\001\000\014\030\040\034\067\036\101\037\052\040" +
    "\037\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\014\030\040\034\067\036" +
    "\107\037\052\040\037\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\030\040\034\067\036\114\037\052\040\037" +
    "\001\001\000\002\001\001\000\014\030\040\034\067\036" +
    "\116\037\052\040\037\001\001\000\002\001\001\000\034" +
    "\005\120\023\055\024\041\025\042\026\057\027\050\030" +
    "\040\031\043\034\063\036\044\037\052\040\037\042\054" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\034\005\126" +
    "\023\055\024\041\025\042\026\057\027\050\030\040\031" +
    "\043\034\063\036\044\037\052\040\037\042\054\001\001" +
    "\000\002\001\001\000\002\001\001\000\034\005\131\023" +
    "\055\024\041\025\042\026\057\027\050\030\040\031\043" +
    "\034\063\036\044\037\052\040\037\042\054\001\001\000" +
    "\002\001\001\000\034\005\135\023\055\024\041\025\042" +
    "\026\057\027\050\030\040\031\043\034\063\036\044\037" +
    "\052\040\037\042\054\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\030\040\034\067\036\141\037\052\040\037" +
    "\001\001\000\002\001\001\000\002\001\001\000\016\030" +
    "\040\034\067\035\144\036\146\037\052\040\037\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\021\162" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\017\172\022\171\042\173\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\022\176\001\001\000\002\001" +
    "\001\000\004\021\200\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\021\203\001\001\000\002\001\001\000" +
    "\022\007\205\010\021\011\022\012\034\014\032\015\025" +
    "\016\015\022\155\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\021\210\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\006\032\216\033\215\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\033\217" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\021\226\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\017\232\022\171\042\173" +
    "\001\001\000\002\001\001\000\002\001\001\000\022\007" +
    "\235\010\021\011\022\012\034\014\032\015\025\016\015" +
    "\022\155\001\001\000\002\001\001\000\004\021\162\001" +
    "\001\000\002\001\001\000\004\020\252\001\001\000\004" +
    "\020\243\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\030\004\260" +
    "\006\017\007\035\010\021\011\022\012\034\013\016\014" +
    "\032\015\025\016\015\022\020\001\001\000\030\004\257" +
    "\006\017\007\035\010\021\011\022\012\034\013\016\014" +
    "\032\015\025\016\015\022\020\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();

public void syntax_error(Symbol symbol)
{
Token token = (Token) symbol.value;
syntaxErrorManager.syntaxError ("Error sintactico, lexema:" + token.getLexema(), token);
}

public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
{
Token token = (Token) symbol.value;
syntaxErrorManager.syntaxFatalError ("Error fatal", token);
}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {



SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
ScopeManagerIF scopeManager = CompilerContext.getScopeManager ();
FinalCodeFactoryIF finalCodeFactory = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // empty ::= 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("empty",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // sentenciaFor ::= FOR IDENTIFIER IN expresion DOUBLEPOINT expresion LOOP bloqueSentencias END LOOP 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaFor",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // listaParametros ::= empty 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // listaParametros ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // listaParametros ::= listaParametros COMMA expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // sentenciaLlamadaSubprograma ::= IDENTIFIER LEFTBRACKET listaParametros RIGHTBRACKET 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaLlamadaSubprograma",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // sentenciaReturn ::= RETURN expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaReturn",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // sentenciaIf ::= IF expresion THEN bloqueSentencias ELSE bloqueSentencias END IF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIf",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // sentenciaIf ::= IF expresion THEN bloqueSentencias END IF 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIf",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // sentenciaAsignacion ::= expresionAccesoRegistro ASSIGN expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // sentenciaAsignacion ::= IDENTIFIER ASSIGN expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // parametro ::= STRING 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // parametro ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // sentenciaIO ::= PUTLINE LEFTBRACKET parametro RIGHTBRACKET 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIO",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // expresionAccesoRegistro ::= IDENTIFIER POINT IDENTIFIER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionAccesoRegistro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // expresionAccesoRegistro ::= IDENTIFIER POINT expresionAccesoRegistro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionAccesoRegistro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // expresionLogica ::= FALSE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // expresionLogica ::= TRUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresionLogica ::= sentenciaLlamadaSubprograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresionLogica ::= expresion EQUAL expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresionLogica ::= expresion GREATTHAN expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresionLogica ::= expresion OR expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresionAritmetica ::= NUMBER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionAritmetica",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresionAritmetica ::= expresion PLUS expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionAritmetica",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresion ::= IDENTIFIER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresion ::= LEFTBRACKET expresion RIGHTBRACKET 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresion ::= expresionAccesoRegistro 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresion ::= expresionLogica 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion ::= expresionAritmetica 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // sentencia ::= sentenciaFor 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // sentencia ::= sentenciaReturn 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // sentencia ::= sentenciaIO 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // sentencia ::= sentenciaIf 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sentencia ::= sentenciaAsignacion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // sentencia ::= expresion 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // bloqueSentencias ::= empty 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueSentencias",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // bloqueSentencias ::= sentencia SEMICOLON bloqueSentencias 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueSentencias",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // bloqueParamSubprograma ::= empty 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueParamSubprograma",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // bloqueParamSubprograma ::= listaIdentificadores COLON tipoPrimitivo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueParamSubprograma",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // bloqueParamSubprograma ::= bloqueParamSubprograma SEMICOLON listaIdentificadores COLON tipoPrimitivo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueParamSubprograma",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // declaracionSubprogramas ::= FUNCTION IDENTIFIER LEFTBRACKET bloqueParamSubprograma RIGHTBRACKET error IS 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 00x: Error definición función, falta return");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // declaracionSubprogramas ::= PROCEDURE IDENTIFIER LEFTBRACKET bloqueParamSubprograma RIGHTBRACKET IS seccionTipos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // declaracionSubprogramas ::= FUNCTION IDENTIFIER LEFTBRACKET bloqueParamSubprograma RIGHTBRACKET RETURN tipoPrimitivo IS seccionTipos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // tipoPrimitivo ::= IDENTIFIER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // tipoPrimitivo ::= BOOLEAN 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // tipoPrimitivo ::= INTEGER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // declaracionVariables ::= listaIdentificadores COLON tipoPrimitivo SEMICOLON 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariables",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // campoRegistro ::= IDENTIFIER COLON tipoPrimitivo 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("campoRegistro",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // bloqueCamposRegistro ::= bloqueCamposRegistro campoRegistro SEMICOLON 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueCamposRegistro",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // bloqueCamposRegistro ::= campoRegistro SEMICOLON 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueCamposRegistro",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declaracionTipos ::= TYPE IDENTIFIER IS RECORD bloqueCamposRegistro END RECORD SEMICOLON 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTipos",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // valorConstante ::= NUMBER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConstante",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // valorConstante ::= FALSE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConstante",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // valorConstante ::= TRUE 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConstante",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // declaracionConstante ::= listaIdentificadores COLON CONSTANT ASSIGN valorConstante error SEMICOLON 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 00x: Error en declaración constantes, falta punto y coma");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstante",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // declaracionConstante ::= listaIdentificadores COLON CONSTANT ASSIGN error 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 00x: Error en declaración constantes, valor incorrecto");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstante",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // declaracionConstante ::= listaIdentificadores COLON CONSTANT error valorConstante 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 00x: Error en declaración constantes, operador asignación");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstante",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // declaracionConstante ::= listaIdentificadores COLON CONSTANT ASSIGN valorConstante SEMICOLON 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxDebug("En declaración constante");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstante",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // listaIdentificadores ::= IDENTIFIER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaIdentificadores",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // listaIdentificadores ::= listaIdentificadores COMMA IDENTIFIER 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaIdentificadores",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // seccionCuerpoPrograma ::= error 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 003: Estructura programa");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionCuerpoPrograma",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // seccionCuerpoPrograma ::= BEGIN bloqueSentencias END error SEMICOLON 
            {
              Object RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 002: Estructura programa, falta NOMBRE_PROGRAMA en sentencia END");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionCuerpoPrograma",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // seccionCuerpoPrograma ::= BEGIN bloqueSentencias END IDENTIFIER SEMICOLON 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionCuerpoPrograma",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // seccionSubprogramas ::= seccionCuerpoPrograma 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionSubprogramas",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // seccionSubprogramas ::= declaracionSubprogramas seccionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionSubprogramas",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // seccionVariables ::= seccionSubprogramas 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionVariables",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // seccionVariables ::= declaracionVariables seccionVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionVariables",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // seccionTipos ::= seccionVariables 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionTipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // seccionTipos ::= declaracionTipos seccionTipos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionTipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // seccionConstantes ::= seccionTipos 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionConstantes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // seccionConstantes ::= declaracionConstante seccionConstantes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionConstantes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // declaraciones ::= seccionConstantes 
            {
              Object RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // axiom ::= PROCEDURE IDENTIFIER LEFTBRACKET RIGHTBRACKET error declaraciones 
            {
              Axiom RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 001: Estructura programa, falta IS");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // axiom ::= PROCEDURE IDENTIFIER LEFTBRACKET error RIGHTBRACKET IS declaraciones 
            {
              Axiom RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 00x: Estructura programa - Procedimiento principal no puede tener parámetros");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // axiom ::= PROCEDURE IDENTIFIER LEFTBRACKET RIGHTBRACKET IS declaraciones 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
   // No modificar esta estructura, aunque se pueden añadir más acciones semánticas
  
   //List intermediateCode = ax.getIntermediateCode ();
   //finalCodeFactory.create (intermediateCode);

  
   syntaxErrorManager.syntaxInfo ("Parsing process ended.");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;

        syntaxErrorManager.syntaxInfo ("Starting parsing...");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

