
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Aug 16 14:35:53 CEST 2014
//----------------------------------------------------

package compiler.syntax;

import java_cup.runtime.Symbol;
import java.util.*;
import es.uned.lsi.compiler.lexical.*;
import es.uned.lsi.compiler.code.*;
import es.uned.lsi.compiler.intermediate.*;
import es.uned.lsi.compiler.semantic.*;
import es.uned.lsi.compiler.semantic.symbol.*;
import es.uned.lsi.compiler.semantic.type.*;
import es.uned.lsi.compiler.syntax.*;
import compiler.CompilerContext;
import compiler.lexical.*;
import compiler.syntax.nonTerminal.*;
import compiler.semantic.*;
import compiler.semantic.symbol.*;
import compiler.semantic.type.*;
import compiler.intermediate.*;
import compiler.code.*;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sat Aug 16 14:35:53 CEST 2014
  */
public class parser extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public parser() {super();}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public parser(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\113\000\002\002\004\000\002\043\002\000\002\002" +
    "\004\000\002\003\002\000\002\044\002\000\002\003\011" +
    "\000\002\004\003\000\002\006\004\000\002\006\003\000" +
    "\002\007\004\000\002\007\003\000\002\010\004\000\002" +
    "\010\003\000\002\011\004\000\002\011\003\000\002\012" +
    "\007\000\002\012\007\000\002\012\003\000\002\022\005" +
    "\000\002\022\003\000\002\013\010\000\002\020\003\000" +
    "\002\020\003\000\002\020\003\000\002\014\012\000\002" +
    "\032\005\000\002\032\004\000\002\033\005\000\002\015" +
    "\006\000\002\021\003\000\002\021\003\000\002\021\003" +
    "\000\002\016\013\000\002\016\011\000\002\016\011\000" +
    "\002\017\007\000\002\017\005\000\002\017\003\000\002" +
    "\005\005\000\002\005\003\000\002\023\003\000\002\023" +
    "\003\000\002\023\003\000\002\023\003\000\002\023\003" +
    "\000\002\023\003\000\002\036\003\000\002\036\003\000" +
    "\002\036\003\000\002\036\005\000\002\036\003\000\002" +
    "\037\005\000\002\037\003\000\002\040\005\000\002\040" +
    "\005\000\002\040\005\000\002\040\003\000\002\040\003" +
    "\000\002\040\003\000\002\034\005\000\002\034\005\000" +
    "\002\024\006\000\002\035\003\000\002\035\003\000\002" +
    "\025\005\000\002\025\005\000\002\026\010\000\002\026" +
    "\012\000\002\027\004\000\002\030\006\000\002\041\005" +
    "\000\002\041\003\000\002\041\003\000\002\031\014\000" +
    "\002\042\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\006\002\000\025\000\001\002\000\004\002" +
    "\250\001\002\000\006\002\ufffe\025\007\001\002\000\004" +
    "\002\uffff\001\002\000\004\004\010\001\002\000\004\035" +
    "\ufffd\001\002\000\004\035\012\001\002\000\004\036\013" +
    "\001\002\000\004\022\014\001\002\000\016\003\027\004" +
    "\030\007\033\016\031\025\023\033\026\001\002\000\012" +
    "\003\027\007\033\016\031\025\023\001\002\000\016\003" +
    "\027\004\030\007\033\016\031\025\023\033\026\001\002" +
    "\000\004\002\ufffb\001\002\000\006\040\157\042\236\001" +
    "\002\000\014\002\ufff5\003\ufff5\007\ufff5\016\ufff5\025\ufff5" +
    "\001\002\000\014\002\ufff7\003\ufff7\007\ufff7\016\ufff7\025" +
    "\ufff7\001\002\000\004\004\230\001\002\000\004\002\ufffc" +
    "\001\002\000\014\003\027\004\030\007\033\016\031\025" +
    "\023\001\002\000\004\004\211\001\002\000\014\002\ufff0" +
    "\003\ufff0\007\ufff0\016\ufff0\025\ufff0\001\002\000\006\040" +
    "\uffee\042\uffee\001\002\000\004\004\167\001\002\000\016" +
    "\003\027\004\030\007\033\016\031\025\023\033\026\001" +
    "\002\000\026\004\050\005\056\013\uffb7\014\061\015\062" +
    "\017\053\026\045\030\047\032\051\035\060\001\002\000" +
    "\014\002\ufff3\003\ufff3\007\ufff3\016\ufff3\025\ufff3\001\002" +
    "\000\004\002\ufff9\001\002\000\026\023\uffd2\024\uffd2\031" +
    "\uffd2\036\uffd2\037\uffd2\040\uffd2\041\uffd2\043\uffd2\044\uffd2" +
    "\045\uffd2\001\002\000\004\013\150\001\002\000\026\023" +
    "\uffc9\024\uffc9\031\uffc9\036\uffc9\037\uffc9\040\uffc9\041\uffc9" +
    "\043\uffc9\044\uffc9\045\uffc9\001\002\000\004\041\uffd6\001" +
    "\002\000\004\041\uffd8\001\002\000\004\041\uffd4\001\002" +
    "\000\014\024\100\041\uffd9\043\076\044\075\045\077\001" +
    "\002\000\004\035\143\001\002\000\004\041\uffd5\001\002" +
    "\000\014\004\066\005\056\014\061\032\051\035\060\001" +
    "\002\000\022\024\uffcf\035\071\041\uffcf\043\uffcf\044\uffcf" +
    "\045\uffcf\046\140\047\070\001\002\000\026\023\uffc8\024" +
    "\uffc8\031\uffc8\036\uffc8\037\uffc8\040\uffc8\041\uffc8\043\uffc8" +
    "\044\uffc8\045\uffc8\001\002\000\026\023\uffd3\024\uffd3\031" +
    "\uffd3\036\uffd3\037\uffd3\040\uffd3\041\uffd3\043\uffd3\044\uffd3" +
    "\045\uffd3\001\002\000\014\004\066\005\056\014\061\032" +
    "\051\035\060\001\002\000\006\012\uffda\013\uffda\001\002" +
    "\000\004\041\125\001\002\000\026\023\uffcd\024\uffcd\031" +
    "\uffcd\036\uffcd\037\uffcd\040\uffcd\041\uffcd\043\uffcd\044\uffcd" +
    "\045\uffcd\001\002\000\004\041\uffd7\001\002\000\014\004" +
    "\066\005\056\014\061\032\051\035\060\001\002\000\026" +
    "\023\uffc7\024\uffc7\031\uffc7\036\uffc7\037\uffc7\040\uffc7\041" +
    "\uffc7\043\uffc7\044\uffc7\045\uffc7\001\002\000\004\004\112" +
    "\001\002\000\016\024\uffd1\041\uffd1\043\uffd1\044\uffd1\045" +
    "\uffd1\046\064\001\002\000\014\004\066\005\056\014\061" +
    "\032\051\035\060\001\002\000\014\024\100\041\uffc0\043" +
    "\076\044\075\045\077\001\002\000\032\023\uffcf\024\uffcf" +
    "\031\uffcf\035\071\036\uffcf\037\uffcf\040\uffcf\041\uffcf\043" +
    "\uffcf\044\uffcf\045\uffcf\047\070\001\002\000\026\023\uffd1" +
    "\024\uffd1\031\uffd1\036\uffd1\037\uffd1\040\uffd1\041\uffd1\043" +
    "\uffd1\044\uffd1\045\uffd1\001\002\000\004\004\110\001\002" +
    "\000\020\004\066\005\056\014\061\032\051\035\060\036" +
    "\uffb7\040\uffb7\001\002\000\006\036\106\040\105\001\002" +
    "\000\006\036\uffb9\040\uffb9\001\002\000\016\024\100\036" +
    "\uffba\040\uffba\043\076\044\075\045\077\001\002\000\014" +
    "\004\066\005\056\014\061\032\051\035\060\001\002\000" +
    "\014\004\066\005\056\014\061\032\051\035\060\001\002" +
    "\000\014\004\066\005\056\014\061\032\051\035\060\001" +
    "\002\000\014\004\066\005\056\014\061\032\051\035\060" +
    "\001\002\000\026\023\uffcc\024\uffcc\031\uffcc\036\uffcc\037" +
    "\uffcc\040\uffcc\041\uffcc\043\uffcc\044\uffcc\045\uffcc\001\002" +
    "\000\026\023\uffca\024\100\031\uffca\036\uffca\037\uffca\040" +
    "\uffca\041\uffca\043\uffca\044\uffca\045\uffca\001\002\000\026" +
    "\023\uffce\024\100\031\uffce\036\uffce\037\uffce\040\uffce\041" +
    "\uffce\043\uffce\044\075\045\077\001\002\000\026\023\uffcb" +
    "\024\100\031\uffcb\036\uffcb\037\uffcb\040\uffcb\041\uffcb\043" +
    "\uffcb\044\uffcb\045\077\001\002\000\014\004\066\005\056" +
    "\014\061\032\051\035\060\001\002\000\026\023\uffbc\024" +
    "\uffbc\031\uffbc\036\uffbc\037\uffbc\040\uffbc\041\uffbc\043\uffbc" +
    "\044\uffbc\045\uffbc\001\002\000\016\024\100\036\uffbb\040" +
    "\uffbb\043\076\044\075\045\077\001\002\000\032\023\uffc5" +
    "\024\uffc5\031\uffc5\036\uffc5\037\uffc5\040\uffc5\041\uffc5\043" +
    "\uffc5\044\uffc5\045\uffc5\046\uffc5\047\070\001\002\000\030" +
    "\023\uffc6\024\uffc6\031\uffc6\036\uffc6\037\uffc6\040\uffc6\041" +
    "\uffc6\043\uffc6\044\uffc6\045\uffc6\046\uffc6\001\002\000\004" +
    "\020\113\001\002\000\014\004\066\005\056\014\061\032" +
    "\051\035\060\001\002\000\014\024\100\037\115\043\076" +
    "\044\075\045\077\001\002\000\014\004\066\005\056\014" +
    "\061\032\051\035\060\001\002\000\014\023\117\024\100" +
    "\043\076\044\075\045\077\001\002\000\026\004\050\005" +
    "\056\013\uffb7\014\061\015\062\017\053\026\045\030\047" +
    "\032\051\035\060\001\002\000\004\013\121\001\002\000" +
    "\004\023\122\001\002\000\004\041\uffb8\001\002\000\014" +
    "\024\100\036\124\043\076\044\075\045\077\001\002\000" +
    "\026\023\uffd0\024\uffd0\031\uffd0\036\uffd0\037\uffd0\040\uffd0" +
    "\041\uffd0\043\uffd0\044\uffd0\045\uffd0\001\002\000\030\004" +
    "\050\005\056\012\uffb7\013\uffb7\014\061\015\062\017\053" +
    "\026\045\030\047\032\051\035\060\001\002\000\006\012" +
    "\uffdb\013\uffdb\001\002\000\014\024\100\031\130\043\076" +
    "\044\075\045\077\001\002\000\030\004\050\005\056\012" +
    "\uffb7\013\uffb7\014\061\015\062\017\053\026\045\030\047" +
    "\032\051\035\060\001\002\000\006\012\132\013\133\001" +
    "\002\000\026\004\050\005\056\013\uffb7\014\061\015\062" +
    "\017\053\026\045\030\047\032\051\035\060\001\002\000" +
    "\004\017\134\001\002\000\004\041\uffbf\001\002\000\004" +
    "\013\136\001\002\000\004\017\137\001\002\000\004\041" +
    "\uffbe\001\002\000\014\004\066\005\056\014\061\032\051" +
    "\035\060\001\002\000\014\024\100\041\uffc1\043\076\044" +
    "\075\045\077\001\002\000\014\024\100\041\uffbd\043\076" +
    "\044\075\045\077\001\002\000\016\004\066\005\056\006" +
    "\145\014\061\032\051\035\060\001\002\000\004\036\147" +
    "\001\002\000\004\036\uffc2\001\002\000\014\024\100\036" +
    "\uffc3\043\076\044\075\045\077\001\002\000\004\041\uffc4" +
    "\001\002\000\006\003\151\004\152\001\002\000\004\041" +
    "\154\001\002\000\004\041\153\001\002\000\014\002\ufff2" +
    "\003\ufff2\007\ufff2\016\ufff2\025\ufff2\001\002\000\014\002" +
    "\ufff1\003\ufff1\007\ufff1\016\ufff1\025\ufff1\001\002\000\006" +
    "\040\157\042\160\001\002\000\014\002\ufff8\003\ufff8\007" +
    "\ufff8\016\ufff8\025\ufff8\001\002\000\004\004\166\001\002" +
    "\000\010\004\163\010\164\021\161\001\002\000\010\022" +
    "\uffe4\036\uffe4\041\uffe4\001\002\000\004\041\165\001\002" +
    "\000\010\022\uffe2\036\uffe2\041\uffe2\001\002\000\010\022" +
    "\uffe3\036\uffe3\041\uffe3\001\002\000\014\003\uffe5\004\uffe5" +
    "\007\uffe5\016\uffe5\025\uffe5\001\002\000\006\040\uffef\042" +
    "\uffef\001\002\000\004\035\170\001\002\000\010\004\030" +
    "\036\uffb7\041\uffb7\001\002\000\006\040\157\042\207\001" +
    "\002\000\006\036\174\041\175\001\002\000\006\036\uffdc" +
    "\041\uffdc\001\002\000\006\003\202\030\201\001\002\000" +
    "\004\004\030\001\002\000\006\040\157\042\177\001\002" +
    "\000\010\004\163\010\164\021\161\001\002\000\006\036" +
    "\uffde\041\uffde\001\002\000\010\004\163\010\164\021\161" +
    "\001\002\000\004\022\203\001\002\000\012\003\uffdf\007" +
    "\uffdf\016\uffdf\025\uffdf\001\002\000\004\022\205\001\002" +
    "\000\016\003\027\004\030\007\033\016\031\025\023\033" +
    "\026\001\002\000\012\003\uffe1\007\uffe1\016\uffe1\025\uffe1" +
    "\001\002\000\010\004\163\010\164\021\161\001\002\000" +
    "\006\036\uffdd\041\uffdd\001\002\000\004\022\212\001\002" +
    "\000\004\027\213\001\002\000\004\004\215\001\002\000" +
    "\004\041\226\001\002\000\004\042\224\001\002\000\006" +
    "\004\215\013\220\001\002\000\004\041\223\001\002\000" +
    "\004\027\221\001\002\000\004\041\222\001\002\000\016" +
    "\003\uffe9\004\uffe9\007\uffe9\016\uffe9\025\uffe9\033\uffe9\001" +
    "\002\000\006\004\uffe8\013\uffe8\001\002\000\010\004\163" +
    "\010\164\021\161\001\002\000\004\041\uffe6\001\002\000" +
    "\006\004\uffe7\013\uffe7\001\002\000\014\002\ufff6\003\ufff6" +
    "\007\ufff6\016\ufff6\025\ufff6\001\002\000\004\035\231\001" +
    "\002\000\010\004\030\036\uffb7\041\uffb7\001\002\000\006" +
    "\036\233\041\175\001\002\000\004\022\234\001\002\000" +
    "\016\003\027\004\030\007\033\016\031\025\023\033\026" +
    "\001\002\000\012\003\uffe0\007\uffe0\016\uffe0\025\uffe0\001" +
    "\002\000\012\004\163\010\164\011\237\021\161\001\002" +
    "\000\004\046\240\001\002\000\010\005\243\014\244\032" +
    "\242\001\002\000\004\041\245\001\002\000\004\041\uffec" +
    "\001\002\000\004\041\uffea\001\002\000\004\041\uffeb\001" +
    "\002\000\016\003\uffed\004\uffed\007\uffed\016\uffed\025\uffed" +
    "\033\uffed\001\002\000\004\002\ufffa\001\002\000\014\002" +
    "\ufff4\003\ufff4\007\ufff4\016\ufff4\025\ufff4\001\002\000\004" +
    "\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\246\000\006\002\003\043\004\001\001\000\002\001" +
    "\001\000\004\003\005\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\044\010\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\030\004\023\006\016" +
    "\007\034\010\021\011\020\012\033\013\015\014\031\015" +
    "\024\016\014\022\017\001\001\000\010\011\246\012\033" +
    "\016\014\001\001\000\026\006\245\007\034\010\021\011" +
    "\020\012\033\013\015\014\031\015\024\016\014\022\017" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\016\010\226\011\020\012\033\015\024\016\014\022" +
    "\154\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\022\007\155\010\021\011" +
    "\020\012\033\014\031\015\024\016\014\022\154\001\001" +
    "\000\034\005\036\023\054\024\040\025\041\026\056\027" +
    "\045\030\037\031\042\034\062\036\043\037\051\040\035" +
    "\042\053\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\030\037" +
    "\034\066\036\141\037\051\040\035\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\014\030\037" +
    "\034\066\036\126\037\051\040\035\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\030\037\034\066\036\122\037\051\040\035\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\014\030\037\034\066\036\064\037\051\040\035\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\034\110\001\001\000\020\030\037\034\066\036" +
    "\073\037\051\040\035\041\071\042\072\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\014\030" +
    "\037\034\066\036\103\037\051\040\035\001\001\000\014" +
    "\030\037\034\066\036\102\037\051\040\035\001\001\000" +
    "\014\030\037\034\066\036\101\037\051\040\035\001\001" +
    "\000\014\030\037\034\066\036\100\037\051\040\035\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\014\030\037\034\066\036\106\037" +
    "\051\040\035\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\030\037\034\066\036\113\037\051\040\035\001\001" +
    "\000\002\001\001\000\014\030\037\034\066\036\115\037" +
    "\051\040\035\001\001\000\002\001\001\000\034\005\117" +
    "\023\054\024\040\025\041\026\056\027\045\030\037\031" +
    "\042\034\062\036\043\037\051\040\035\042\053\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\034\005\125\023\054" +
    "\024\040\025\041\026\056\027\045\030\037\031\042\034" +
    "\062\036\043\037\051\040\035\042\053\001\001\000\002" +
    "\001\001\000\002\001\001\000\034\005\130\023\054\024" +
    "\040\025\041\026\056\027\045\030\037\031\042\034\062" +
    "\036\043\037\051\040\035\042\053\001\001\000\002\001" +
    "\001\000\034\005\134\023\054\024\040\025\041\026\056" +
    "\027\045\030\037\031\042\034\062\036\043\037\051\040" +
    "\035\042\053\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\014\030\037\034\066\036\140\037\051\040\035\001\001" +
    "\000\002\001\001\000\002\001\001\000\016\030\037\034" +
    "\066\035\143\036\145\037\051\040\035\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\021\161\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\017\171\022\170\042\172\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\022\175\001\001\000\002\001\001\000" +
    "\004\021\177\001\001\000\002\001\001\000\004\021\203" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\022\007\205\010\021\011\020\012\033\014\031" +
    "\015\024\016\014\022\154\001\001\000\002\001\001\000" +
    "\004\021\207\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\032\215\033\213\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\033\216\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\021\224\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\017\231\022\170\042\172\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\007\234\010" +
    "\021\011\020\012\033\014\031\015\024\016\014\022\154" +
    "\001\001\000\002\001\001\000\004\021\161\001\001\000" +
    "\002\001\001\000\004\020\240\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$parser$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$parser$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$parser$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



	SyntaxErrorManager syntaxErrorManager = CompilerContext.getSyntaxErrorManager();
	
	public void syntax_error(Symbol symbol)
	{ 
	    Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxError ("Error sintactico", token);	    
	}
		
	public void unrecovered_syntax_error(java_cup.runtime.Symbol symbol)
	{	
		Token token = (Token) symbol.value;
	    syntaxErrorManager.syntaxFatalError ("Error fatal", token);
	}

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$parser$actions {


	
	SyntaxErrorManager   syntaxErrorManager   = CompilerContext.getSyntaxErrorManager();
	SemanticErrorManager semanticErrorManager = CompilerContext.getSemanticErrorManager ();
	ScopeManagerIF       scopeManager         = CompilerContext.getScopeManager ();
	FinalCodeFactoryIF   finalCodeFactory     = CompilerContext.getFinalCodeFactory ();


  private final parser parser;

  /** Constructor */
  CUP$parser$actions(parser parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$parser$do_action(
    int                        CUP$parser$act_num,
    java_cup.runtime.lr_parser CUP$parser$parser,
    java.util.Stack            CUP$parser$stack,
    int                        CUP$parser$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$parser$result;

      /* select the action based on the action number */
      switch (CUP$parser$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // empty ::= 
            {
              Empty RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("empty",32, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // sentenciaFor ::= FOR IDENTIFIER IN expresion DOUBLEPOINT expresion LOOP bloqueSentencias END LOOP 
            {
              SentenciaFor RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaFor",23, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-9)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // listaParametros ::= empty 
            {
              ListaParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // listaParametros ::= expresion 
            {
              ListaParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",31, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // listaParametros ::= listaParametros COMMA expresion 
            {
              ListaParametros RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaParametros",31, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // sentenciaLlamadaSubprograma ::= IDENTIFIER LEFTBRACKET listaParametros RIGHTBRACKET 
            {
              SentenciaLlamadaSubprograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaLlamadaSubprograma",22, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // sentenciaReturn ::= RETURN expresion 
            {
              SentenciaReturn RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaReturn",21, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // sentenciaIf ::= IF expresion THEN bloqueSentencias ELSE bloqueSentencias END IF 
            {
              SentenciaIf RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIf",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // sentenciaIf ::= IF expresion THEN bloqueSentencias END IF 
            {
              SentenciaIf RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIf",20, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // sentenciaAsignacion ::= expresionAccesoRegistro ASSIGN expresion 
            {
              SentenciaAsignacion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // sentenciaAsignacion ::= IDENTIFIER ASSIGN expresion 
            {
              SentenciaAsignacion RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int expleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int expright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion exp = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								
								//Comprobamos si se ha definido el símbolo en la TS anteriormente, si no, mostramos error semántico								
								ScopeIF scope = scopeManager.getCurrentScope();																
								SymbolTableIF tablaSimbolos = scope.getSymbolTable();										
								if(!tablaSimbolos.containsSymbol(id.getLexema())){
									semanticErrorManager.semanticFatalError("ERROR: Variable " + id.getLexema() + " not defined - Line=" + id.getLine() + ",Col=" + id.getColumn());
								}			
								else{
									//Comprobación de tipos.
									SymbolIF symbol = scopeManager.searchSymbol(id.getLexema());
									TypeIF idtype = symbol.getType();
									semanticErrorManager.semanticDebug("El tipo de la variable: " + id.getLexema() + " es: " + idtype.getName());
									//TypeIF exptype = exp.getType();
								}
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaAsignacion",19, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // parametro ::= STRING 
            {
              Parametro RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // parametro ::= expresion 
            {
              Parametro RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("parametro",27, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // sentenciaIO ::= PUTLINE LEFTBRACKET parametro RIGHTBRACKET 
            {
              SentenciaIO RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentenciaIO",18, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // expresionAccesoRegistro ::= IDENTIFIER POINT IDENTIFIER 
            {
              ExpresionAccesoRegistro RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionAccesoRegistro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // expresionAccesoRegistro ::= IDENTIFIER POINT expresionAccesoRegistro 
            {
              ExpresionAccesoRegistro RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionAccesoRegistro",26, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // expresionLogica ::= FALSE 
            {
              ExpresionLogica RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // expresionLogica ::= TRUE 
            {
              ExpresionLogica RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // expresionLogica ::= sentenciaLlamadaSubprograma 
            {
              ExpresionLogica RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // expresionLogica ::= expresion EQUAL expresion 
            {
              ExpresionLogica RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								ExpresionLogica e = new ExpresionLogica(e1, e2);
								//Comprobación de tipos sobre e1 y e2
								//Generación de código para e1 = e2
								RESULT=e;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // expresionLogica ::= expresion GREATTHAN expresion 
            {
              ExpresionLogica RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								ExpresionLogica e = new ExpresionLogica(e1, e2);
								//Comprobación de tipos sobre e1 y e2
								//Generación de código para e1 > e2
								RESULT = e;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // expresionLogica ::= expresion OR expresion 
            {
              ExpresionLogica RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								ExpresionLogica e = new ExpresionLogica(e1, e2);
								//Comprobación de tipos sobre e1 y e2
								//Generación de código para e1 OR e2							
								RESULT = e;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionLogica",30, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // expresionAritmetica ::= NUMBER 
            {
              ExpresionAritmetica RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionAritmetica",29, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // expresionAritmetica ::= expresion PLUS expresion 
            {
              ExpresionAritmetica RESULT =null;
		int e1left = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int e1right = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Expresion e1 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int e2left = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int e2right = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Expresion e2 = (Expresion)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								
//								//Comprobación de tipos sobre e1 y e2
//								TypeIF e1type = scopeManager.searchType("Integer");
//								TypeIF e2type = scopeManager.searchType("Integer");
//								semanticErrorManager.semanticDebug("Expresión Aritmética - Tipo de e1: " + e1type.getName());
//								semanticErrorManager.semanticDebug("Expresión Aritmética - Tipo de e2: " + e2type.getName());
//								if (e1type == e2type)
//								{
//									semanticErrorManager.semanticDebug("Expresión Aritmética - Tipos compatibles" );							
//								}
//								else semanticErrorManager.semanticFatalError ("Expresión Aritmética - Tipos incompatibles");

								ExpresionAritmetica e = new ExpresionAritmetica(e1, e2);
								RESULT = e; 
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresionAritmetica",29, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // expresion ::= IDENTIFIER 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // expresion ::= LEFTBRACKET expresion RIGHTBRACKET 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // expresion ::= expresionAccesoRegistro 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // expresion ::= expresionLogica 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // expresion ::= expresionAritmetica 
            {
              Expresion RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("expresion",28, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // sentencia ::= sentenciaFor 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // sentencia ::= sentenciaReturn 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // sentencia ::= sentenciaIO 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // sentencia ::= sentenciaIf 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // sentencia ::= sentenciaAsignacion 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // sentencia ::= expresion 
            {
              Sentencia RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("sentencia",17, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // bloqueSentencias ::= empty 
            {
              BloqueSentencias RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueSentencias",3, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // bloqueSentencias ::= sentencia SEMICOLON bloqueSentencias 
            {
              BloqueSentencias RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueSentencias",3, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // bloqueParamSubprograma ::= empty 
            {
              BloqueParamSubprograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueParamSubprograma",13, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // bloqueParamSubprograma ::= listaIdentificadores COLON tipoPrimitivo 
            {
              BloqueParamSubprograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueParamSubprograma",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // bloqueParamSubprograma ::= bloqueParamSubprograma SEMICOLON listaIdentificadores COLON tipoPrimitivo 
            {
              BloqueParamSubprograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueParamSubprograma",13, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // declaracionSubprogramas ::= FUNCTION IDENTIFIER LEFTBRACKET bloqueParamSubprograma RIGHTBRACKET error IS 
            {
              DeclaracionSubprogramas RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 00x: Error definición función, falta return");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // declaracionSubprogramas ::= PROCEDURE IDENTIFIER LEFTBRACKET bloqueParamSubprograma RIGHTBRACKET IS seccionTipos 
            {
              DeclaracionSubprogramas RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // declaracionSubprogramas ::= FUNCTION IDENTIFIER LEFTBRACKET bloqueParamSubprograma RIGHTBRACKET RETURN tipoPrimitivo IS seccionTipos 
            {
              DeclaracionSubprogramas RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionSubprogramas",12, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-8)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // tipoPrimitivo ::= IDENTIFIER 
            {
              TipoPrimitivo RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			TipoPrimitivo tipoPrim = new TipoPrimitivo(id.getLexema());
									RESULT = tipoPrim;
								
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // tipoPrimitivo ::= BOOLEAN 
            {
              TipoPrimitivo RESULT =null;
		int tpboolleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tpboolright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token tpbool = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 TipoPrimitivo tipoPrim = new TipoPrimitivo(tpbool.getLexema());
								 	RESULT = tipoPrim;
								 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // tipoPrimitivo ::= INTEGER 
            {
              TipoPrimitivo RESULT =null;
		int tpintleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tpintright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token tpint = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 TipoPrimitivo tipoPrim = new TipoPrimitivo(tpint.getLexema());
								 	RESULT = tipoPrim;
								 
              CUP$parser$result = parser.getSymbolFactory().newSymbol("tipoPrimitivo",15, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // declaracionVariables ::= listaIdentificadores COLON tipoPrimitivo SEMICOLON 
            {
              DeclaracionVariables RESULT =null;
		int lidleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int lidright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		ListaIdentificadores lid = (ListaIdentificadores)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		int tpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int tpright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		TipoPrimitivo tp = (TipoPrimitivo)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
			//	Obtenemos ámbito actual
								ScopeIF scope = scopeManager.getCurrentScope();
								semanticErrorManager.semanticDebug("Sección Declaración Variables: Scope actual, nombre:" + scope.getName());
								
								// Obtenemos la tabla de símbolos del ámbito actual, y verificamos si los identificadores de la lista de variables están ya definidos en la TS
								SymbolTableIF tablaSimbolos = scope.getSymbolTable();
								semanticErrorManager.semanticDebug("Tabla símbolos del scope:" + scope.getName() + " obtenida. Tamaño TS: " + tablaSimbolos.getSize());
								ArrayList<String> identifiersList = lid.getIdentifiersList();
								semanticErrorManager.semanticDebug("Tras obtener lista de Identificadores como ArrayList. Tamaño ArrayList=" + identifiersList.size());
								for(int i = 0; i<identifiersList.size(); i++){
									if(tablaSimbolos.containsSymbol(identifiersList.get(i)))
										semanticErrorManager.semanticFatalError("Error en declaración de Variable, ya existe declaración de " + identifiersList.get(i));
									else{ 
										TypeIF tipo = scopeManager.searchType("Integer");
										SymbolVariable symbolvariable = new SymbolVariable(scope, identifiersList.get(i), tipo);
										tablaSimbolos.addSymbol(symbolvariable);
									}
								}
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionVariables",11, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // campoRegistro ::= IDENTIFIER COLON tipoPrimitivo 
            {
              CampoRegistro RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int tpleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int tpright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		TipoPrimitivo tp = (TipoPrimitivo)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
								CampoRegistro camporeg = new CampoRegistro(id.getLexema(), tp);
								RESULT = camporeg;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("campoRegistro",25, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // bloqueCamposRegistro ::= campoRegistro SEMICOLON 
            {
              BloqueCamposRegistro RESULT =null;
		int crleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int crright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		CampoRegistro cr = (CampoRegistro)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
								BloqueCamposRegistro bloquecampos = new BloqueCamposRegistro();
								bloquecampos.addCampoRegistro(cr);
								RESULT = bloquecampos;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueCamposRegistro",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // bloqueCamposRegistro ::= bloqueCamposRegistro campoRegistro SEMICOLON 
            {
              BloqueCamposRegistro RESULT =null;
		int bcrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int bcrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		BloqueCamposRegistro bcr = (BloqueCamposRegistro)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int crleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int crright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		CampoRegistro cr = (CampoRegistro)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		
								BloqueCamposRegistro bloquecampos = bcr;
								bloquecampos.addCampoRegistro(cr);
								RESULT = bloquecampos;
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("bloqueCamposRegistro",24, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // declaracionTipos ::= TYPE IDENTIFIER IS RECORD bloqueCamposRegistro END RECORD SEMICOLON 
            {
              DeclaracionTipos RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-6)).value;
		int bcrleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).left;
		int bcrright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-3)).right;
		BloqueCamposRegistro bcr = (BloqueCamposRegistro)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-3)).value;
		// Obtenemos ámbito actual
								ScopeIF scope = scopeManager.getCurrentScope();
								semanticErrorManager.semanticDebug("****Sección Declaración Tipos*****: Scope actual, nombre:" + scope.getName());
								semanticErrorManager.semanticDebug("**********************************");

								// Obtenemos la tabla de tipos del ámbito actual,y verificamos si el tipo está definido ya en TT, si no, lo añadimos								
								TypeTableIF tablaTipos = scope.getTypeTable();
								if(tablaTipos.containsType(id.getLexema()))
										semanticErrorManager.semanticFatalError("ERROR - Error en declaración de Tipo, ya existe declaración de " + id.getLexema());
								else{ 
									//Creamos nuevo tipo Registro y lo introducimos en la tabla de tipos
									TypeRecord typerec = new TypeRecord(scope, id.getLexema(), bcr);
									tablaTipos.addType(id.getLexema(), typerec);
									semanticErrorManager.semanticDebug("Tipo Record: " + id.getLexema() + " añadido a TT del scope:" + scope.getName() + " (tamañoTT=" + tablaTipos.getSize() + ")");
									
									TypeRecord tipoRegistro = (TypeRecord) tablaTipos.getType(id.getLexema());
									semanticErrorManager.semanticDebug("Campos en Registro (leyendo de TT)- RECORD: " + tipoRegistro.getName() + ", Num. campos=" + tipoRegistro.getSize());
									for (int j=0; j < tipoRegistro.getBloqueCampos().getListaCamposRegistro().size(); j++){
										semanticErrorManager.semanticDebug("     " + tipoRegistro.getBloqueCampos().getListaCamposRegistro().get(j).getName() +
												":" + tipoRegistro.getBloqueCampos().getListaCamposRegistro().get(j).getTipo().getValue() );
									}
									
								}
								semanticErrorManager.semanticDebug("FIN ****Sección Declaración Tipos*****: Scope actual, nombre:" + scope.getName());
								semanticErrorManager.semanticDebug("**********************************");								
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionTipos",10, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-7)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // valorConstante ::= NUMBER 
            {
              ValorConstante RESULT =null;
		int numleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int numright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token num = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 	
				   	 		ValorConstante value = new ValorConstante(num.getLexema());
				   	 		RESULT = value;
				   	 	
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConstante",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // valorConstante ::= FALSE 
            {
              ValorConstante RESULT =null;
		int vcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vcright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token vc = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			ValorConstante value = new ValorConstante(vc.getLexema());
				   			RESULT = value; 
				   		
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConstante",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // valorConstante ::= TRUE 
            {
              ValorConstante RESULT =null;
		int vcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int vcright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token vc = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
							ValorConstante value = new ValorConstante(vc.getLexema());
					   		RESULT = value; 
					   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("valorConstante",14, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // declaracionConstante ::= listaIdentificadores COLON CONSTANT ASSIGN valorConstante SEMICOLON 
            {
              DeclaracionConstante RESULT =null;
		int lidleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int lidright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		ListaIdentificadores lid = (ListaIdentificadores)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int vcleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int vcright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		ValorConstante vc = (ValorConstante)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		syntaxErrorManager.syntaxDebug("En declaración constante");
							
								//	Obtenemos ámbito actual
								ScopeIF scope = scopeManager.getCurrentScope();
								semanticErrorManager.semanticDebug("Scope actual, nombre:" + scope.getName());
								// Obtenemos la tabla de símbolos del ámbito actual
								SymbolTableIF tablaSimbolos = scope.getSymbolTable();
								semanticErrorManager.semanticDebug("Tabla símbolos del scope:" + scope.getName() + " obtenida. Tamaño TS: " + tablaSimbolos.getSize());
								
								// Obtenemos lista de identificadores
								ArrayList<String> identifiersList = lid.getIdentifiersList();
								semanticErrorManager.semanticDebug("Tras obtener lista de Identificadores como ArrayList. Tamaño ArrayList=" + identifiersList.size());
								
								//Verificamos si los identificadores de la lista están ya definidos en la TS. 
								for(int i = 0; i<identifiersList.size(); i++){
									if(tablaSimbolos.containsSymbol(identifiersList.get(i)))
										semanticErrorManager.semanticFatalError("Error en declaración de Constante, ya existe declaración de " + identifiersList.get(i));
									else{
										// Símbolos no existen en TS, por lo que añadimos cada uno de ellos a la TS.		
										// SymbolConstant(scope, name, type)
										TypeIF typeInTT = scopeManager.searchType("Boolean");
										SymbolConstant symbolconstant = new SymbolConstant(scope, identifiersList.get(i), typeInTT);
										tablaSimbolos.addSymbol(symbolconstant);
									}
								}
							
              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaracionConstante",9, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // listaIdentificadores ::= IDENTIFIER 
            {
              ListaIdentificadores RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
			
						  	//Creamos lista de identificadores, e insertamos el primer elemento id.
						  	ListaIdentificadores idlist = new ListaIdentificadores();
						  	semanticErrorManager.semanticDebug("Tras creación listaIdentificadores. Size = " + idlist.getSize());
						  	idlist.addIdentifier(id.getLexema());
						  	semanticErrorManager.semanticDebug("Tras añadir identificador: " + id.getLexema() + ", listaIdentificadores. Size = " + idlist.getSize() );
						  	RESULT=idlist;
						  
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaIdentificadores",16, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // listaIdentificadores ::= listaIdentificadores COMMA IDENTIFIER 
            {
              ListaIdentificadores RESULT =null;
		int idlistleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).left;
		int idlistright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)).right;
		ListaIdentificadores idlist = (ListaIdentificadores)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-2)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		
							String name = id.getLexema();
							//Verificamos si el identificador está en la tabla de símbolos
							if(scopeManager.containsSymbol(name)){
								//Si existe el símbolo en ámbitos abiertos, lo obtenemos,
								SymbolIF sym = scopeManager.searchSymbol(name);
								if (sym instanceof SymbolConstant){
									SymbolConstant symconst = (SymbolConstant)sym;
									Object value = symconst.getValue();
									//RESULT = new RNumero(value);
								}
								else
									semanticErrorManager.semanticFatalError("Símbolo no es de tipo SymbolConstant");
							}
							else{
								//Añadimos identificador a lista de identificadores
								idlist.addIdentifier(id.getLexema());
								RESULT=idlist;
								}					
						
              CUP$parser$result = parser.getSymbolFactory().newSymbol("listaIdentificadores",16, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-2)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // seccionCuerpoPrograma ::= error 
            {
              SeccionCuerpoPrograma RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 003: Estructura programa");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionCuerpoPrograma",8, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // seccionCuerpoPrograma ::= BEGIN bloqueSentencias END error SEMICOLON 
            {
              SeccionCuerpoPrograma RESULT =null;
		syntaxErrorManager.syntaxInfo("ERROR 002: Estructura programa, falta NOMBRE_PROGRAMA en sentencia END");
              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionCuerpoPrograma",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // seccionCuerpoPrograma ::= BEGIN bloqueSentencias END IDENTIFIER SEMICOLON 
            {
              SeccionCuerpoPrograma RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionCuerpoPrograma",8, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-4)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // seccionSubprogramas ::= seccionCuerpoPrograma 
            {
              SeccionSubprogramas RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionSubprogramas",7, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // seccionSubprogramas ::= declaracionSubprogramas seccionSubprogramas 
            {
              SeccionSubprogramas RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionSubprogramas",7, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // seccionVariables ::= seccionSubprogramas 
            {
              SeccionVariables RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionVariables",6, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // seccionVariables ::= declaracionVariables seccionVariables 
            {
              SeccionVariables RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionVariables",6, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // seccionTipos ::= seccionVariables 
            {
              SeccionTipos RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionTipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // seccionTipos ::= declaracionTipos seccionTipos 
            {
              SeccionTipos RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionTipos",5, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // seccionConstantes ::= seccionTipos 
            {
              SeccionConstantes RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionConstantes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // seccionConstantes ::= declaracionConstante seccionConstantes 
            {
              SeccionConstantes RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("seccionConstantes",4, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // declaraciones ::= seccionConstantes 
            {
              Declaraciones RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("declaraciones",2, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // axiom ::= PROCEDURE IDENTIFIER NT$1 LEFTBRACKET RIGHTBRACKET IS declaraciones 
            {
              Axiom RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Axiom) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-4)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-5)).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-5)).value;
		int dleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int dright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Declaraciones d = (Declaraciones)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-6)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // NT$1 ::= 
            {
              Axiom RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Token id = (Token)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;

			//Creación del ámbito global del programa
				String name = id.getLexema();
				scopeManager.openScope(name);
				ScopeIF scope = scopeManager.getCurrentScope();
				semanticErrorManager.semanticDebug("El nombre del scope creado es: " + scope.getName());
				
				//Obtenemos la tabla de tipos del ámbito actual
				TypeTableIF tablaTipos = scope.getTypeTable();
				semanticErrorManager.semanticDebug("Tabla de tipos obtenida, pertenece al scope/ámbito: " + tablaTipos.getScope().getName() + " y tiene tamaño: " + tablaTipos.getSize()); 
				
				//Insertar todos los TypeSimple en la Tabla de Tipos
				TypeSimple typeBoolean = new TypeSimple(scope, "Boolean");
				TypeSimple typeInteger = new TypeSimple(scope, "Integer");
				tablaTipos.addType("Boolean", typeBoolean);
				tablaTipos.addType("Integer", typeInteger); 
				semanticErrorManager.semanticDebug("Tabla de tipos obtenida del scope/ámbito: " + tablaTipos.getScope().getName() + " y tiene tamaño: " + tablaTipos.getSize());
				List<TypeIF> listaTipos = tablaTipos.getTypes();
				semanticErrorManager.semanticDebug("TT contiente tipo Boolean??" + tablaTipos.containsType("Boolean"));
					semanticErrorManager.semanticDebug("TT contiente tipo Integer??" + tablaTipos.containsType("Integer"));
					semanticErrorManager.semanticDebug("TT contiente tipo Pepe??" + tablaTipos.containsType("Pepe"));
				for (int i=0; i<listaTipos.size(); i++){
					semanticErrorManager.semanticDebug("Nombre de tipo: " + listaTipos.get(i).getName());
				}
				
				//scopeManager.closeScope();
				//semanticErrorManager.semanticDebug("Scope cerrado: " + scope.getName());
			
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$1",34, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // axiom ::= 
            {
              Axiom RESULT =null;

              CUP$parser$result = parser.getSymbolFactory().newSymbol("axiom",1, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // program ::= NT$0 axiom 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		int axleft = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).left;
		int axright = ((java_cup.runtime.Symbol)CUP$parser$stack.peek()).right;
		Axiom ax = (Axiom)((java_cup.runtime.Symbol) CUP$parser$stack.peek()).value;
		 
  		// No modificar esta estructura, aunque se pueden añadir más acciones semánticas
  		
  		//List intermediateCode = ax.getIntermediateCode ();
  		//finalCodeFactory.create (intermediateCode);

  		
  		syntaxErrorManager.syntaxInfo ("Parsing process ended.");
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("program",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // NT$0 ::= 
            {
              Object RESULT =null;
 
        syntaxErrorManager.syntaxInfo ("Starting parsing..."); 
   
              CUP$parser$result = parser.getSymbolFactory().newSymbol("NT$0",33, ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          return CUP$parser$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= program EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$parser$stack.elementAt(CUP$parser$top-1)).value;
		RESULT = start_val;
              CUP$parser$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$parser$stack.elementAt(CUP$parser$top-1)), ((java_cup.runtime.Symbol)CUP$parser$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$parser$parser.done_parsing();
          return CUP$parser$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

