
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Sep 08 16:22:32 CEST 2014
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LEFTBRACKET = 27;
  public static final int DOUBLEPOINT = 29;
  public static final int FUNCTION = 12;
  public static final int RIGHTBRACKET = 28;
  public static final int INTEGER = 15;
  public static final int BACKSLASH = 26;
  public static final int FOR = 11;
  public static final int SEMICOLON = 31;
  public static final int IS = 16;
  public static final int RECORD = 21;
  public static final int TYPE = 25;
  public static final int IN = 14;
  public static final int OR = 18;
  public static final int COMMA = 30;
  public static final int BEGIN = 5;
  public static final int LOOP = 17;
  public static final int PLUS = 33;
  public static final int ASSIGN = 36;
  public static final int IF = 13;
  public static final int EOF = 0;
  public static final int BOOLEAN = 6;
  public static final int RETURN = 22;
  public static final int EQUAL = 35;
  public static final int GREATTHAN = 34;
  public static final int TRUE = 24;
  public static final int error = 1;
  public static final int NUMBER = 3;
  public static final int CONSTANT = 7;
  public static final int PUTLINE = 20;
  public static final int COLON = 32;
  public static final int ELSE = 8;
  public static final int POINT = 37;
  public static final int THEN = 23;
  public static final int END = 9;
  public static final int STRING = 4;
  public static final int FALSE = 10;
  public static final int PROCEDURE = 19;
  public static final int IDENTIFIER = 2;
}

