
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Aug 04 21:02:52 CEST 2014
//----------------------------------------------------

package compiler.syntax;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int LEFTBRACKET = 29;
  public static final int DOUBLEPOINT = 31;
  public static final int FUNCTION = 13;
  public static final int RIGHTBRACKET = 30;
  public static final int INTEGER = 16;
  public static final int BACKSLASH = 28;
  public static final int ARRAY = 5;
  public static final int FOR = 12;
  public static final int SEMICOLON = 33;
  public static final int IS = 17;
  public static final int RECORD = 23;
  public static final int TYPE = 27;
  public static final int IN = 15;
  public static final int OR = 20;
  public static final int COMMA = 32;
  public static final int BEGIN = 6;
  public static final int PLUS = 35;
  public static final int LOOP = 18;
  public static final int ASSIGN = 38;
  public static final int IF = 14;
  public static final int OF = 19;
  public static final int EOF = 0;
  public static final int BOOLEAN = 7;
  public static final int RETURN = 24;
  public static final int EQUAL = 37;
  public static final int GREATTHAN = 36;
  public static final int TRUE = 26;
  public static final int error = 1;
  public static final int NUMBER = 3;
  public static final int CONSTANT = 8;
  public static final int PUTLINE = 22;
  public static final int COLON = 34;
  public static final int ELSE = 9;
  public static final int POINT = 39;
  public static final int THEN = 25;
  public static final int END = 10;
  public static final int STRING = 4;
  public static final int FALSE = 11;
  public static final int PROCEDURE = 21;
  public static final int IDENTIFIER = 2;
}

